### ISSUE TITLE
Scrap's Junk/Useful tabs not displaying anything

### ISSUE THREAD

**Issue by javedbartlett** [Jaliborc/Scrap#101]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to vendor
2. Click on scrap tab
3. Click either junk or useful
4. Nothing is displayed, just an empty box

**Expected behaviour**
Supposed to display things i've added to the list.

**Screenshots**
https://i.imgur.com/dDOnwxx.png

**Error Logs**
None.

**Additional context**

**Comment by Blobson** [comment]
Same here!

**Comment by AgamlaRage** [comment]
+1

**Comment by Jaliborc** [comment]
Works for me, IDK why its empty on your end

**Comment by KyrosKrane** [comment]
This happens for me when I open the Scrap tab on a toon with a very large list of scrap items. It's just Scrap trying to load all the item information. If I leave that tab open for an extended period, it will eventually populate. It just takes a REALLY long time on my main that has hundreds of items marked as scrap.

**Comment by Jaliborc** [comment]
> This happens for me when I open the Scrap tab on a toon with a very large list of scrap items. It's just Scrap trying to load all the item information. If I leave that tab open for an extended period, it will eventually populate. It just takes a REALLY long time on my main that has hundreds of items marked as scrap.

Ah, I see. Not sure how to fix that. Stuff gotta load...

**Comment by Jaliborc** [comment]
Changed it so it shows items that are ready as it loads more.

**Comment by SteadEXE** [comment]
It is still empty even after leaving the window opened for a long time
