### ISSUE TITLE
Lua error with Shadowlands

### ISSUE THREAD

**Issue by Vachon8449** [Jaliborc/Scrap#105]
**Running Software (issues missing this information will be deleted):** I'm not sure what you mean by running software. I'm running windows 10 and world of warcraft shadowlands.
 - Addon version: Scrap version 8.3.2-8.3.0.zip 
 - Server patch: [e.g. Build 8.0.1.27178] version 9.0.2.36165

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. I have read the top portion of it, the issue involved is for 9.093 which isn't listed.

**Describe the bug**
When I click on a vendor with items to sell in my bag I get 4 Lua Errors:
Message: Interface\AddOns\Scrap\addons\main\main.lua:189:attempt to compare nil with number
Time: Tue Oct 13 23:05:23 2020
Count 4
Stack: I'm sorry I can't re-type the entire error messages. 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Well, what was happening before Shadowlands was I'd click on a vendor and Scrap would auto sell all my unusable items all at once. I guess that's the expected behaviour for this error? 

**Screenshots**

I have a screenshot, but I'm unsure how to get it to you. I don't see anything about attacking a file. 

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by rainfordays** [comment]
People have added pull requests but he doesn't seem to be too active on this addon anymore.

Here's a fork that I just updated to have at least basic functionallity https://github.com/rainfordays/Scrap

**Comment by gaveer** [comment]
```
1x Scrap\addons\main\main.lua:189: attempt to compare nil with number
[string "@Scrap\addons\main\main.lua"]:189: in function 'IsStandardQuality'
[string "@Scrap\addons\main\main.lua"]:162: in function 'IsFiltered'
[string "@Scrap\addons\main\main.lua"]:95: in function 'IsJunk'
[string "@Scrap\addons\main\main.lua"]:127: in function '(for generator)'
[string "@Scrap\addons\merchant\button.lua"]:215: in function 'GetReport'
[string "@Scrap\addons\merchant\button.lua"]:187: in function 'Sell'
[string "@Scrap\addons\merchant\button.lua"]:62: in function 'OnMerchant'
[string "@Scrap\addons\merchant\button.lua"]:45: in function '?'
[string "@Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
[string "@Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]:"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function 'Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]:"]: ?
[string "=[C]:"]: in function 'LoadAddOn'
[string "@Scrap\addons\main\main.lua"]:52: in function <Scrap\addons\main\main.lua:52>
[string "=[C]:"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function 'Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>```

**Comment by Hampen555** [comment]
Hm, doesnt work for me even with Rainfordays' version

**Comment by gaveer** [comment]
you mean by : 
1- the addone not working 
2- or the addone dont give errors

**Comment by rainfordays** [comment]
Do you get any errors?

**Comment by Hampen555** [comment]
Unfortunately no (I assume that would make troubleshooting a lot easier), I don't see the buttons on the merchant frame, but I can access the settings from Interface. I think I have the right files? What I did was replacing the scrap main folder from Twitch with your version, so I currently have these 3 scrap folders in my addons folder https://imgur.com/a/XqcLgQp

**Comment by Hampen555** [comment]
I just noticed that in my Addon Control Panel window it says that Scrap Merchant and Scrap Options are missing a Dependency, hm weird. I looked into the scrap-master folder and these are the files I have
https://imgur.com/a/D368apv

**Comment by rainfordays** [comment]
Remove the old Scrap folder and then Rename the folder you downloaded from **Scrap-master** to just **Scrap**

**Comment by Hampen555** [comment]
Unfortunately that didnt do anything, still nothing :/ 

However I did try to add something to my junklist and then I got this lua error 

2x [string "SCRAP_TOGGLE"]:3: attempt to index global 'Scrap' (a nil value)
[string "SCRAP_TOGGLE"]:3: in function <[string "SCRAP_TOGGLE"]:1>

Locals:
keystate = "down"
item = "|cffffffff|Hitem:152579::::::::50:262:::::::|h[Storm Silver Ore]|h|r"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "|cffffffff|Hitem:152579::::::::50:262:::::::|h[Storm Silver Ore]|h|r"
(*temporary) = "Storm Silver Ore"
(*temporary) = "|cffffffff|Hitem:152579::::::::50:262:::::::|h[Storm Silver Ore]|h|r"
(*temporary) = nil
(*temporary) = "attempt to index global 'Scrap' (a nil value)"

**Comment by rainfordays** [comment]
What it's saying is that the addon Scrap isn't loaded.

You downloaded the thing from my branch, the folder that you get is called 'Scrap-master', it has to be named just 'Scrap'. 

In your addons folder there should be

- Scrap
- Scrap_Config
- Scrap_Merchant

**Comment by Hampen555** [comment]
Yep i got those

https://imgur.com/a/VwGeMrf

**Comment by gaveer** [comment]
@Hampen555  do you see this folder named **Scrap-master**  in this folder ?  https://imgur.com/a/XqcLgQp  


you need to rename it to `Scrap`only

**Comment by Hampen555** [comment]
Yeah i fixed that, see the last pic, still not working

**Comment by gaveer** [comment]
so you have twitch client running on the background on auto update ?     -  can you type your discord if you have it

**Comment by Hampen555** [comment]
Sure Hampen#1337

**Comment by Hampen555** [comment]
Me and Gaveer fixed it in discord, the issue was on my end, the addon is working for me now
