### ISSUE TITLE
Selling stuff that is not junk

### ISSUE THREAD

**Issue by Nephorax** [Jaliborc/Scrap#109]
6529/shiny-bauble
136377/oversized-bobber
160705/majors-frothy-coffee
More Etc..

trying to fish and was wondering why everything was gone from my bags.. thats just theses items... maybe more but didnt notice...
all the gold lost!

I love this addon plz make a fix for stuff like this. Thx 

Keep up the good work!

**Comment by Jaliborc** [comment]
Added!
