### ISSUE TITLE
Error opening void storage

### ISSUE THREAD

**Issue by BradCOnGitHub** [Jaliborc/Scrap#126]
Message: Interface\AddOns\Scrap\addons\main\main.lua:225: attempt to compare number with string
Time: Wed Mar 17 20:21:04 2021
Count: 1
Stack: Interface\AddOns\Scrap\addons\main\main.lua:225: attempt to compare number with string
[string "@Interface\AddOns\Scrap\addons\main\main.lua"]:225: in function `GuessBagSlot'
[string "@Interface\AddOns\Scrap\addons\main\main.lua"]:214: in function `GuessLocation'
[string "@Interface\AddOns\Scrap\addons\main\main.lua"]:136: in function `IsFiltered'
[string "@Interface\AddOns\Scrap\addons\main\main.lua"]:79: in function `IsJunk'
[string "@Interface\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua"]:42: in function `UpdateBorder'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua"]:197: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua"]:40: in function <...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:34>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\itemGroup.lua"]:124: in function <...AddOns\Bagnon\common\Wildpants\classes\itemGroup.lua:113>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\vault\itemGroup.lua"]:48: in function `func'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua"]:36: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>

Locals: self = <table> {
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 Merchant = <unnamed> {
 }
 PrintMoney = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:277
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 IterateJunk = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:91
 IsBetterEquip = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:201
 tip = ScrapTooltip {
 }
 charsets = <table> {
 }
 GuessLocation = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:213
 IsStandardQuality = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:172
 LoadTip = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:252
 ScanLine = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:269
 Spotlight = <table> {
 }
 IsCombatItem = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:176
 Visualizer = ScrapVisualizer {
 }
 Tag = "SCRAP_"
 Tutorials = <table> {
 }
 Learning = <table> {
 }
 IsLowLevel = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:168
 numLines = 15
 DestroyJunk = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:118
 ToggleJunk = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:83
 Print = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:281
 Wildpants = <table> {
 }
 junk = <table> {
 }
 sets = <table> {
 }
 limit = 2
 baseList = <table> {
 }
 GuessBagSlot = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:223
 SendMessage = <function> defined @Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 OnSettings = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:65
 UnregisterAllEvents = <function> defined @Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 IsJunk = <function> defined @Interface\AddOns\Scrap\addons\main\main.lua:77
 Options = <unnamed> {
 }
 RegisterMessage = <function> defined @Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 RegisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UnregisterMessage = <function> defined @Interface\AddOns\AllTheTh

**Comment by Jaliborc** [comment]
Ohh, Bagnon Scrap issue I presume. Fixed
