### ISSUE TITLE
[Classic  ERA] lua error

### ISSUE THREAD

**Issue by waytoomuchgaming** [Jaliborc/Scrap#133]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.0.6
 - Server patch: 1.13.7

 **Have you read the changelog? (please don't waste our time)**
yes

**Describe the bug**
1x Scrap\addons\merchant\visualizer.lua:131: attempt to compare number with nil
Scrap\addons\merchant\visualizer.lua:131: in function <Scrap\addons\merchant\visualizer.lua:119>
[C]: in function `sort'
Scrap\addons\merchant\visualizer.lua:119: in function `UpdateList'
Scrap\addons\merchant\visualizer.lua:54: in function <Scrap\addons\merchant\visualizer.lua:52>
[C]: in function `SetShown'
Scrap\libs\SecureTabs-2.0\SecureTabs-2.0-2.lua:91: in function `Update'
Scrap\libs\SecureTabs-2.0\SecureTabs-2.0-2.lua:64: in function `Select'
Scrap\libs\SecureTabs-2.0\SecureTabs-2.0-2.lua:42: in function <Scrap\libs\SecureTabs-2.0\SecureTabs-2.0.lua:42>

Locals:
A = 961
B = 4540
nameA = nil
_ = nil
qualityA = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
classA = nil
nameB = "Tough Hunk of Bread"
_ = "|cffffffff|Hitem:4540::::::::12:::::::|h[Tough Hunk of Bread]|h|r"
qualityB = 1
_ = 5
_ = 1
_ = "Consumable"
_ = "Consumable"
_ = 20
_ = ""
_ = 133964
_ = 1
classB = 0
(*temporary) = 1
(*temporary) = "attempt to compare number with nil"

**To Reproduce**
uncheck "character specific junklist" option, then talk to a merchant

**Comment by waytoomuchgaming** [comment]
That other one looks very similar, so i'm not opening another issue (no idea if i should or not, just tell me):

1x Scrap\addons\merchant\visualizer.lua:129: attempt to compare two nil values
Scrap\addons\merchant\visualizer.lua:129: in function <Scrap\addons\merchant\visualizer.lua:119>
[C]: in function `sort'
Scrap\addons\merchant\visualizer.lua:119: in function `?'
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `SendMessage'
...ceScrap\libs\WildAddon-1.0\WildAddon-1.0-1.lua:83: in function `SendSignal'
Scrap\addons\main\main.lua:71: in function `?'
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `SendMessage'
...ceScrap\libs\WildAddon-1.0\WildAddon-1.0-1.lua:83: in function `SendSignal'
Scrap\addons\config\options.lua:40: in function `method'
...ddOns\Scrap\libs\Sushi-3.1-4\classes\core\Callable.lua:53: in function `FireCalls'
...s\Scrap\libs\Sushi-3.1-4\classes\buttons\Clickable.lua:39: in function <...s\Scrap\libs\Sushi-3.1\classes\buttons\Clickable.lua:34>

**Comment by Jaliborc** [comment]
Added check to prevent
