### ISSUE TITLE
[TBCC] Error on Login / ReloadUI

### ISSUE THREAD

**Issue by heyiamsven** [Jaliborc/Scrap#136]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.0.6
 - Server patch: TBCC latest

 **Have you read the changelog? (please don't waste our time)**
x

**Describe the bug**
Lua Error after Login / ReloadUI

**To Reproduce**
Steps to reproduce the behaviour:
See "Describe the bug"

**Expected behaviour**
No error

**Error Logs**

> Message: ...face\AddOns\Scrap\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
> Time: Tue Jun 15 19:00:14 2021
> Count: 1
> Stack: ...face\AddOns\Scrap\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
> [string "=(tail call)"]: ?
> [string "=[C]"]: in function `RegisterEvent'
> [string "@Interface\AddOns\Scrap\libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
> [string "@Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
> [string "@Interface\AddOns\Prat-3.0\modules\PlayerNames.lua"]:1132: in function `OnModuleEnable'
> [string "@Interface\AddOns\Prat-3.0\addon\modules.lua"]:189: in function <Interface\AddOns\Prat-3.0\addon\modules.lua:178>
> [string "=[C]"]: ?
> [string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
> [string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
> [string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
> [string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:615>
> 
> Locals: <none>

**Comment by Jaliborc** [comment]
Different mod
