### ISSUE TITLE
Need a way to ignore specific grey items without having them

### ISSUE THREAD

**Issue by BradCOnGitHub** [Jaliborc/Scrap#138]
Blizzard did something stupid and made some grey items useful:

https://www.wowhead.com/npc=156769/keeper-tahult#comments

We need a way to ignore these items in Scrap.

**Comment by sig-daveka** [comment]
This would also be useful to prevent sale of the gray items needed to purchase baubleworms.

**Comment by Jaliborc** [comment]
Fear not, they are now not trash by default
