### ISSUE TITLE
error in 8.0

### ISSUE THREAD

**Issue by Daeveren** [Jaliborc/Scrap#14]
getting this error in patch 8.0.1 on live servers

> Message: Interface\AddOns\Scrap\Scrap.lua:272: attempt to call global 'CanUseEquipmentSets' (a nil value)
Time: Wed Jul 18 12:27:42 2018
Count: 1
Stack: Interface\AddOns\Scrap\Scrap.lua:272: attempt to call global 'CanUseEquipmentSets' (a nil value)
[C]: in function `CanUseEquipmentSets'
Interface\AddOns\Scrap\Scrap.lua:272: in function `BelongsToSet'
Interface\AddOns\Scrap\Scrap.lua:181: in function `CheckFilters'
Interface\AddOns\Scrap\Scrap.lua:116: in function `IsJunk'
Interface\AddOns\ElvUI_Scrap\ElvUI_Scrap.lua:17: in function <Interface\AddOns\ElvUI_Scrap\ElvUI_Scrap.lua:4>
[C]: in function `UpdateSlot'
Interface\AddOns\ElvUI\Modules\bags\bags.lua:575: in function `UpdateBagSlots'
Interface\AddOns\ElvUI\Modules\bags\bags.lua:602: in function `UpdateAllSlots'
Interface\AddOns\ElvUI\Modules\bags\bags.lua:1777: in function `OpenBags'
Interface\AddOns\ElvUI\Modules\bags\bags.lua:1742: in function <Interface\AddOns\ElvUI\Modules\bags\bags.lua:1736>
(tail call): ?
[C]: in function `ToggleBag'
Interface\FrameXML\ContainerFrame.lua:139: in function <Interface\FrameXML\ContainerFrame.lua:122>
[C]: in function `ToggleBackpack'
Interface\FrameXML\ContainerFrame.lua:359: in function <Interface\FrameXML\ContainerFrame.lua:340>
[C]: in function `OpenBackpack'
Interface\FrameXML\ContainerFrame.lua:1503: in function <Interface\FrameXML\ContainerFrame.lua:1480>
[C]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:

**Comment by BelegCufea** [comment]
quick fix:
 - Scrap.lua (line 272)
original:
`return CanUseEquipmentSets() and GetLine(self.numLines - 1):find(IN_SET)`

fix:
`return C_EquipmentSet.CanUseEquipmentSets() and GetLine(self.numLines - 1):find(IN_SET)`

**Comment by Daeveren** [comment]
Thanks, that worked perfectly! 👍
