### ISSUE TITLE
How to exclude trash items needed to buy Baubleworm pets?

### ISSUE THREAD

**Issue by ThrusterNYC** [Jaliborc/Scrap#143]
Hi, 

Love scrap. Thank you for creating it. 

In Shadowlands there are 9 trash items needed to buy 3 Baubleworm pets.

https://eu.forums.blizzard.com/en/wow/t/91-buying-baubleworms-with-greys/271384

Now that I know, I realize I've probably vendored them repeatedly. 

How can I prevent these from being automatically vendored?

It might be nice to have a preference that's on by default for:

✅ Exclude trash items needed to purchase pets / special items

Sure, people would wonder why certain trash were still hanging around in their bags. But at least it would be a sort of heads up, "hey, you might want these". 

If you're feeling super fancy, the first time one of these items are in the player's bags at a vendor, you could pop up "Hey, you've got a trash item needed to purchase pets / special items. Do you want to [ALWAYS KEEP SPECIAL TRASH] or [ALWAYS VENDOR SPECIAL TRASH]?"

Yeah, popups aren't exactly how Scrap works. But it could be very useful and appreciated to alert players that some trash isn't worthless. If I'd figured all this out sooner, I probably could have bought these pets months ago.

Thanks again for a great addon.

Peace.

**Comment by Protuhj** [comment]
I made an AdiBags plugin for this: https://www.curseforge.com/wow/addons/adibags-baubleworm-junk
