### ISSUE TITLE
flagging items 

### ISSUE THREAD

**Issue by kacprzewski** [Jaliborc/Scrap#144]
Add a flagging item for later sail at it was in the paddler

 _"CTRL+Right-click on an item in your inventory and it will be flagged for peddling at your next trip to a vendor! A small set of coins appears in the item's icon to highlight that it will be automatically sold."_
and 
_"Modifier Key - allows the user to change the marking modifier from the CTRL-key."_

**Comment by Jaliborc** [comment]
Check keybindings...
