### ISSUE TITLE
wrong interface version in classic toc file

### ISSUE THREAD

**Issue by MyTechnoHunter** [Jaliborc/Scrap#145]
**Running Software (issues missing this information will be deleted):**
 - Addon version: scrap-9.1.2-1.14.0
 - Server patch: Build 1.14.01

 **Have you read the changelog? (please don't waste our time)**
yes

**Describe the bug**
the interface version in the toc file makes you have to enable load out of date addons

**To Reproduce**
Steps to reproduce the behaviour:
install addon from curseforge
start game. see message about out of date addons

**Expected behaviour**
load cleanly

**Screenshots**
![image](https://user-images.githubusercontent.com/55214545/144554482-15d1475c-a602-4f6e-8465-0684c0cb9adf.png)

please update the toc for classic 

thanks!

**Comment by Jaliborc** [comment]
Can you type `/dump GetBuildInfo()` in the chat and copy here what comes out?

**Comment by Jaliborc** [comment]
Currently battle.net is bugged for some people and doesn't let me start classic.
