### ISSUE TITLE
Destroying items

### ISSUE THREAD

**Issue by Plusader** [Jaliborc/Scrap#147]
Hi there.

I have just installed this addon since another didnt work correctly anymore.

I have found the same bug (it seems its on blizzards side) in your program now.

When destroying items, which are already on the Junk-/Scrap-List, and using the provided hotkey a window without text opens up.

If you choose OK, only one item gets destroyed.
All items on that list should be destroyed though.

**Comment by Dufrange** [comment]
I am having a similar issue, It keeps selling my Goblin glider kits, and I go into the Junk/not junk tab, and there is nothing in the window to toggle as junk / not junk.

**Comment by Jaliborc** [comment]
window only shows items you;ve already tagged as junk or not

**Comment by Jaliborc** [comment]
don't skip tutorials
