### ISSUE TITLE
Can't flag item as non junk

### ISSUE THREAD

**Issue by simsekb** [Jaliborc/Scrap#148]
The tab that's meant for that is disabled. It keeps selling items I don't want to be sold.

**Comment by Qwickdraw** [comment]
well thats fucked up.. mine does the same. Sells EVERYTHING

**Comment by Qwickdraw** [comment]
Yea this keeps selling things I NEED, and also sells BOE's....uninstalling but thanks for the run.

**Comment by Qwickdraw** [comment]
Same here. Keeps selling things I need and I cannot mark them "useful".

**Comment by Qwickdraw** [comment]
Hmmmmm, maybe this is supported anymore. I dont see any replies that are recent.
