### ISSUE TITLE
Junk/Useful tab not populating

### ISSUE THREAD

**Issue by PsyberWolf** [Jaliborc/Scrap#149]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Latest
 - Server patch: [e.g. Build 8.0.1.27178] 9.1.5

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. yup

**Describe the bug**
The junk/useful tabs don't populate so you can mark what is useful, what is junk

**To Reproduce**
Steps to reproduce the behaviour:
Open the scrap tab at the bottom.  Junk is blank.
switch to useful at the top, Useful is blank

**Expected behaviour**
I expected the tabs to be filled so I can say what is junk and what isn't (incase there is a gray or something item I don't want sold no matter what)

**Screenshots**
![image](https://user-images.githubusercontent.com/6184663/166159843-9605cec6-e4f9-402c-b336-4ae61f60fe35.png)

**Comment by PsyberWolf** [comment]
This is what I expected:
![image](https://user-images.githubusercontent.com/6184663/166159902-72c1cbb4-77df-424f-992c-5b2d958508db.png)

**Comment by Lasion** [comment]
Hi,
having the same problem. The list doesnt populate so if you accidentally sell an item, it goes to the 'junk' filter and will re-sell each time you open a vendor, which is fairly problematic.

**Comment by Jaliborc** [comment]
Enable lua errors. Cannot do anything without a full error report.

**Comment by Lasion** [comment]
Hi, sorry didn't see your reply before now.
There are no LUA errors. I have Buggrabber and Bugsack enabled, and no errors are reported, but the list still does not populate.
Tested on a character now with only Buggrabber, Bugsack and Scrap enabled. Still no success.
![2022-11-15 16_19_43-World of Warcraft](https://user-images.githubusercontent.com/8824330/201958537-662d4997-60f1-46c8-90be-cb14b1e223f0.png)
![2022-11-15 16_19_53-World of Warcraft](https://user-images.githubusercontent.com/8824330/201958547-51953105-85e6-4cdd-96e7-c76a2ef3947e.png)
