### ISSUE TITLE
LUA errors

### ISSUE THREAD

**Issue by squish88** [Jaliborc/Scrap#155]
Message: Interface\AddOns\Scrap\addons\merchant\learning.lua:44: attempt to index field 'auto' (a nil value)
Time: Tue Sep  6 14:28:08 2022
Count: 1
Stack: Interface\AddOns\Scrap\addons\merchant\learning.lua:44: attempt to index field 'auto' (a nil value)
[string "@Interface\FrameXML\ContainerFrame.lua"]:1284: in function `ContainerFrameItemButton_OnClick'
[string "*:OnClick"]:12: in function <[string "*:OnClick"]:1>

Locals: self = ContainerFrame1Item17 {
 GetItemLocation = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:418
 matchesSearch = true
 SetItem = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:355
 IconOverlay = <unnamed> {
 }
 shouldAnimateStatic = true
 OnItemContextChanged = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:256
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\ContainerFrame.lua:1439
 showMatchHighlight = true
 newitemglowAnim = <unnamed> {
 }
 icon = ContainerFrame1Item17IconTexture {
 }
 isExtended = false
 UpdateTooltip = <function> defined @Interface\FrameXML\ContainerFrame.lua:1345
 LevelLinkLockTexture = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:269
 SetAlpha = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:430
 SetItemButtonCount = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:422
 NewItemTexture = <unnamed> {
 }
 SetItemInternal = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:360
 count = 20
 itemContextMatchResult = 3
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:292
 timeSinceUpgradeCheck = 0
 flashAnim = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnEvent = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:273
 flash = <unnamed> {
 }
 GetItemID = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:399
 SetItemSource = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:339
 IconBorder = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 BattlepayItemTexture = <unnamed> {
 }
 hasItem = 1
 IconOverlay2 = <unnamed> {
 }
 0 = <userdata>
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:287
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:307
 GetDebugReportInfo = <function> defined @Interface\FrameXML\ContainerFrame.lua:1076
 SetItemLocation = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:343
 GetItemLink = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:414
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:260
 GetItemInfo = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:386
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:296
 readable = false
 Count = ContainerFrame1Item17Count {
 }
 GetItemButtonCount = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:426
 Stock = ContainerFrame1Item17Stock {
 }
 searchOverlay = ContainerFrame1Item17SearchOverlay {
 }
 GetItem = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:410
 Reset = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:330
}
button = "RightButton"

Message: Interface\AddOns\Scrap\addons\merchant\learning.lua:44: attempt to index field 'auto' (a nil value)
Time: Tue Sep  6 15:01:56 2022
Count: 19
Stack: Interface\AddOns\Scrap\addons\merchant\learning.lua:44: attempt to index field 'auto' (a nil value)

**Comment by Jaliborc** [comment]
Reload and it will go away. Reset settings otherwise.
