### ISSUE TITLE
CurseForge overwrite version 10.0.2 with 9.2.7

### ISSUE THREAD

**Issue by Scaver** [Jaliborc/Scrap#165]
The version 10-9.2.7 is marked as newer then the 10-10.0.2 at curseforge.
So the CurseForge client always want to overwrite the 10.0.2 version with the 9.2.7.

**Comment by Fleymour** [comment]
yeah there alot of version.. needs anyway some lua fixes:
https://i.imgur.com/zjJvrSi.png

**Comment by Jaliborc** [comment]
Does 10.0.4 overtake it now?

**Comment by Scaver** [comment]
Can'T see any 10.0.4 vrersion on CurseForge.

**Comment by Fleymour** [comment]
new version seems good with installing on curseforge  @Jaliborc 

![CurseForge_cEWfWe8LSz](https://user-images.githubusercontent.com/74535695/203931491-e43f094c-ef32-46e2-a8de-1047d886a272.png)

**Comment by Scaver** [comment]
Wrong AddOn Fleymour!

![Screenshot 2022-11-25 164226](https://user-images.githubusercontent.com/9563058/204018493-52e72ea1-6a13-4d33-bca0-003dbfbebf2e.png)

**Comment by Jaliborc** [comment]
No, right addon. this is scrap.

**Comment by schnoodly** [comment]
Bagnon Scrap still defaults to 9.2.7 on CurseForge — though I'm not  sure if this is still waiting on Bagnon's stable 10.0 release.

**Comment by schnoodly** [comment]
I believe what Scaver was saying, that Fleymore's second post uses normal Scrap, not Bagnon Scrap, from CurseForge. This is still an issue:
![image](https://user-images.githubusercontent.com/20142693/205386265-cd6b5f35-c974-4eb3-8530-0e51e1eb8209.png)
I have manually installed 10.0.2 for now, but it's still pretty annoying that I can't hit my "Update All" button anymore.

**Comment by Scaver** [comment]
> I believe what Scaver was saying, that Fleymour's second post uses normal Scrap, not Bagnon Scrap, from CurseForge. This is still an issue:

Yes, that's exactly what I meant to say.

**Comment by schnoodly** [comment]
> No, right addon. this is scrap.

Any chance of looking at this? The original submitter's issue wasn't fixed.
