### ISSUE TITLE
Junk not marked as Junk in ArkInventory

### ISSUE THREAD

**Issue by codengine** [Jaliborc/Scrap#168]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.0.3
 - Server patch: [e.g. Build 8.0.1.27178] 10.0.0.46597

 **Have you read the changelog? (please don't waste our time)**
- [x]  Mark if read.

**Describe the bug**
I'm using ArkInventory 3.10.04 together with Scrap 10.0.0.3 and so far, I love this addon. However, I noticed since the launch of 10.0 that scrap is not marked as Scrap in ArkInventory anymore. It did work before though. I'm also not sure if it's a bug related to Scrap or ArkInventory.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download Scrap
2. Download ArkInventory
3. Mark something as junk

**Expected behaviour**
Items being marked as Junk

**Screenshots**
ArkInventory:
![grafik](https://user-images.githubusercontent.com/498798/202039624-daa481ae-e62d-4d92-bf09-25a7c5817d20.png)

Default, without ArkInventory:
![grafik](https://user-images.githubusercontent.com/498798/202039666-266df41d-2bf1-4f1c-899b-bb51436565b4.png)

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by Jaliborc** [comment]
Not supported
