### ISSUE TITLE
Opening Bags Error Message 

### ISSUE THREAD

**Issue by Mason-101** [Jaliborc/Scrap#177]
Scrap-10.0.3-10.0.0

There seems to be an issue with this addon and the new AdiBags update, as  Adibags works perfectly fine with out Scrap turned off but the second you turn such on and open your bags you get the following: 

112x Scrap/addons/main/main.lua:228: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/Filters.lua"]:146: in function `Filter'
[string "@AdiBags/widgets/ContainerFrame.lua"]:797: in function `FilterSlot'
[string "@AdiBags/widgets/ContainerFrame.lua"]:831: in function `DispatchItem'
[string "@AdiBags/widgets/ContainerFrame.lua"]:1001: in function `RedispatchAllItems'
[string "@AdiBags/widgets/ContainerFrame.lua"]:1159: in function `FullUpdate'
[string "@AdiBags/widgets/ContainerFrame.lua"]:607: in function <AdiBags/widgets/ContainerFrame.lua:593>
[string "=[C]"]: ?
[string "@AdiBags/core/Utility.lua"]:102: in function <AdiBags/core/Utility.lua:94>
[string "@AdiBags/widgets/LayeredRegion.lua"]:119: in function <AdiBags/widgets/LayeredRegion.lua:108>

Also if I disable Adibags and just open my normal game default bags I get the following with this addon installed: 

350x Scrap/addons/main/spotlight.lua:54: attempt to call global 'GetContainerItemID' (a nil value)
[string "@Scrap/addons/main/spotlight.lua"]:54: in function `UpdateButton'
[string "@Scrap/addons/main/spotlight.lua"]:47: in function `call'
[string "@Scrap/addons/main/spotlight.lua"]:73: in function `IterateFrames'
[string "@Scrap/addons/main/spotlight.lua"]:46: in function `UpdateContainer'
[string "@Scrap/addons/main/spotlight.lua"]:32: in function <Scrap/addons/main/spotlight.lua:32>
[string "=[C]"]: in function `Update'
[string "@FrameXML/ContainerFrame.lua"]:1133: in function `ContainerFrame_GenerateFrame'
[string "@FrameXML/ContainerFrame.lua"]:138: in function `ToggleBag_Individual'
[string "@FrameXML/ContainerFrame.lua"]:156: in function <FrameXML/ContainerFrame.lua:148>
[string "=[C]"]: in function `ToggleBag'
[string "@FrameXML/ContainerFrame.lua"]:107: in function `ToggleBackpack_Individual'
[string "@FrameXML/ContainerFrame.lua"]:119: in function `ToggleBackpack'
[string "@FrameXML/ContainerFrame.lua"]:290: in function `OpenBackpack'
[string "@FrameXML/ContainerFrame.lua"]:1826: in function <FrameXML/ContainerFrame.lua:1825>
[string "@FrameXML/ContainerFrame.lua"]:1888: in function <FrameXML/ContainerFrame.lua:1859>
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = <table> {
 SendSignal = <function> defined @PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @ActionBarProfiles/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ActionBarProfiles/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 IterateFrames = <function> defined @Scrap/addons/main/spotlight.lua:69
 SendMessage = <function> defined @ActionBarProfiles/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 UnregisterSignal = <function> defined @PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 NewIcon = <function> defined @Scrap/addons/main/spotlight.lua:95
 UpdateAll = <function> defined @Scrap/addons/main/spotlight.lua:39
 UpdateButton = <function> defined @Scrap/addons/main/spotlight.lua:51
 RegisterEvent = <function> defined @ActionBarProfiles/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @ActionBarProfiles/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 Icons = <table> {
 }
 Glows = <table> {
 }
 NewGlow = <function> defined @Scrap/addons/main/spotlight.lua:83
 OnEnable = <function> defined @Scrap/addons/main/spotlight.lua:24
 UpdateContainer = <function> defined @Scrap/addons/main/spotlight.lua:45
 RegisterSignal = <function> defined @PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 NewModule = <function> defined @PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 UnregisterAllEvents = <function> defined @ActionBarProfiles/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 UnregisterEvent = <function> defined @ActionBarProfiles/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Tag = "SCRAP_"
}
frame = ContainerFrame1 {
 0 = <userdata>
 CheckAuthenticatorSlotsHelpTip = <function> defined @FrameXML/ContainerFrame.lua:1062
 UpdateMoneyFrame = <function> defined @FrameXML/ContainerFrame.lua:730
 UpdateFilterIcon = <function> defined @FrameXML/ContainerFrame.lua:922
 GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
 GetPaddingWidth = <function> defined @FrameXML/ContainerFrame.lua:849
 SetPortraitTexCoord = <function> defined @SharedXML/PortraitFrame.lua:87
 size = 20
 CheckUpdateDynamicContents = <function> defined @FrameXML/ContainerFrame.lua:822
 UpdateIfShown = <function> defined @FrameXML/ContainerFrame.lua:1048
 GetBagID = <function> defined @FrameXML/ContainerFrame.lua:746
 SetPortraitToBag = <function> defined @SharedXML/PortraitFrame.lua:75
 refresh = <table> {
 }
 TitleContainer = Frame {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 Center = Texture {
 }
 RightEdge = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 UpdateItemContextMatching = <function> defined @FrameXML/ContainerFrame.lua:1080
 BottomEdge = Texture {
 }
 LayoutAddSlots = <function> defined @FrameXML/ContainerFrame.lua:2346
 SetTitle = <function> defined @SharedXML/PortraitFrame.lua:36
 OnCloseClicked = <function> defined @FrameXML/ContainerFrame.lua:726
 UpdateCurrencyFrames = <function> defined @FrameXML/ContainerFrame.lua:2397
 TopEdge = Texture {
 }
 GetInitialItemAnchor = <function> defined @FrameXML/ContainerFrame.lua:2427
 PixelSnapDisabled = true
 CalculateHeight = <function> defined @FrameXML/ContainerFrame.lua:833
 Update = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 SetPortraitAtlasRaw = <function> defined @Inter

Seems there must be some issues still to iron out but just adding it to the list, hopefully it helps

**Comment by Fleymour** [comment]
ALOT OF 
x Scrap/addons/main/spotlight.lua:54: attempt to call global 'GetContainerItemID' (a nil value)
[string "@Scrap/addons/main/spotlight.lua"]:54: in function `UpdateButton'
[string "@Scrap/addons/main/spotlight.lua"]:47: in function `call'
[string "@Scrap/addons/main/spotlight.lua"]:73: in function `IterateFrames'
[string "@Scrap/addons/main/spotlight.lua"]:46: in function `UpdateContainer'
[string "@Scrap/addons/main/spotlight.lua"]:41: in function `call'
[string "@Scrap/addons/main/spotlight.lua"]:73: in function `IterateFrames'
[string "@Scrap/addons/main/spotlight.lua"]:40: in function `UpdateAll'
[string "@Scrap/addons/main/spotlight.lua"]:35: in function <Scrap/addons/main/spotlight.lua:35>
[string "=[C]"]: in function `Update'
[string "@FrameXML/ContainerFrame.lua"]:1133: in function `ContainerFrame_GenerateFrame'
[string "@FrameXML/ContainerFrame.lua"]:196: in function <FrameXML/ContainerFrame.lua:194>
[string "@FrameXML/ContainerFrame.lua"]:220: in function `OpenBag'
[string "@FrameXML/ContainerFrame.lua"]:285: in function `OpenBackpack'
[string "@FrameXML/ContainerFrame.lua"]:1826: in function <FrameXML/ContainerFrame.lua:1825>
[string "@FrameXML/ContainerFrame.lua"]:1888: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = <table> {
 SendSignal = <function> defined @Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 IterateFrames = <function> defined @Scrap/addons/main/spotlight.lua:69
 SendMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:54
 UnregisterSignal = <function> defined @Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 NewIcon = <function> defined @Scrap/addons/main/spotlight.lua:95
 UpdateAll = <function> defined @Scrap/addons/main/spotlight.lua:39
 UpdateButton = <function> defined @Scrap/addons/main/spotlight.lua:51
 RegisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterAllMessages = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 Icons = <table> {
 }
 Glows = <table> {
 }
 NewGlow = <function> defined @Scrap/addons/main/spotlight.lua:83
 OnEnable = <function> defined @Scrap/addons/main/spotlight.lua:24
 UpdateContainer = <function> defined @Scrap/addons/main/spotlight.lua:45
 RegisterSignal = <function> defined @Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 NewModule = <function> defined @Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 UnregisterAllEvents = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 UnregisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 Tag = "SCRAP_"
}
frame = ContainerFrame1 {
 0 = <userdata>
 CheckAuthenticatorSlotsHelpTip = <function> defined @FrameXML/ContainerFrame.lua:1062
 UpdateMoneyFrame = <function> defined @FrameXML/ContainerFrame.lua:730
 UpdateFilterIcon = <function> defined @FrameXML/ContainerFrame.lua:922
 GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
 GetPaddingWidth = <function> defined @FrameXML/ContainerFrame.lua:849
 SetPortraitTexCoord = <function> defined @SharedXML/PortraitFrame.lua:87
 CheckUpdateDynamicContents = <function> defined @FrameXML/ContainerFrame.lua:822
 UpdateIfShown = <function> defined @FrameXML/ContainerFrame.lua:1048
 GetBagID = <function> defined @FrameXML/ContainerFrame.lua:746
 TitleContainer = Frame {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 Center = Texture {
 }
 RightEdge = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 UpdateItemContextMatching = <function> defined @FrameXML/ContainerFrame.lua:1080
 BottomEdge = Texture {
 }
 LayoutAddSlots = <function> defined @FrameXML/ContainerFrame.lua:2346
 SetTitle = <function> defined @SharedXML/PortraitFrame.lua:36
 OnCloseClicked = <function> defined @FrameXML/ContainerFrame.lua:726
 UpdateCurrencyFrames = <function> defined @FrameXML/ContainerFrame.lua:2397
 TopEdge = Texture {
 }
 GetInitialItemAnchor = <function> defined @FrameXML/ContainerFrame.lua:2427
 PixelSnapDisabled = true
 CalculateHeight = <function> defined @FrameXML/ContainerFrame.lua:833
 Update = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 SetPortraitAtlasRaw = <function> defined @SharedXML/PortraitFrame.lua:83
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 CancelRefresh = <function> defined @FrameXML/ContainerFrame.lua:963
 MatchesBagID = <function> defined @FrameXML/ContainerFrame.l
