### ISSUE TITLE
Is this Addon dead?

### ISSUE THREAD

**Issue by duanefalk** [Jaliborc/Scrap#178]
There have been quite a few reports of problems with SCRAP, but I havent seen any info from the developers, and it is still not worknig. Has this addon been abandoned? It's very useful and has always, up to 10.0, worked like a charm.

Could we please get some feedback on wshether you;re working on fixing it? Can it be fixed after 10.0?

Waited with bated breath

**Comment by TomNookman** [comment]
read the update from patreon [https://www.patreon.com/posts/dragonflight-to-73893585](url)

**Comment by Fleymour** [comment]
only patreons can read that.. whats the tldr?

**Comment by duanefalk** [comment]
See the icon when selling but cant click it and scrap doesnt auto sellRegards, DuaneOn Nov 22, 2022, at 4:12 PM, Fleymour ***@***.***> wrote:﻿

read the update from patreon https://www.patreon.com/posts/dragonflight-to-73893585
only patreons can read that.. whats the tldr?

**Comment by duanefalk** [comment]
Yup works fine now! Thanks very much- very useful addon
