### ISSUE TITLE
Global item list between characters

### ISSUE THREAD

**Issue by Deusdictum** [Jaliborc/Scrap#180]
**Is your feature request related to a problem? Please describe.**
I play a lot of alts and have to add a lot of non-grey items as Junk, because they are often have the same or similar sell price to a vendor as they do on an auction house. Or when I'm done collecting some items and want them to mark as junk across all my characters at once. It goes for mats, low-level daily/world quest rewards, etc.

**Describe the solution you'd like**
An option in the settings to enable or disable the global database/list.

**Describe alternatives you've considered**
A profile system like most addons have.

**Comment by Noshei** [comment]
there is an option for this, it defaults to character specific lists, but you can uncheck it for a global list

![image](https://user-images.githubusercontent.com/8866000/203881057-b1f7fdb8-a55c-4710-bc31-1c137cf20a02.png)

**Comment by Deusdictum** [comment]
I guess my eyes refused to see that there is something there, because that part of the UI is global for all settings and I haven't seen other addons use it. Thanks a lot!
