### ISSUE TITLE
Sell Low/Unusable equipment doesn't work

### ISSUE THREAD

**Issue by Mkorny** [Jaliborc/Scrap#183]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.4 (latest - updated this morning)
 - Server patch: 10.0.2 (current Retail)

 **Have you read the changelog? (please don't waste our time)**
 Check!

**Describe the bug**
The filter settings to sell Low or Unusuable equipment is not working (items are not sold)

**To Reproduce**
Steps to reproduce the behaviour:
1. Select the option -> Filter -> Sell Unusable Equipment (or Low Equipment)
2. Confirm you have lowbie BOP items in your inv, or unusable BOP items
3. Interact with any merchant
4. Confirm these items are not sold

**Expected behaviour**
The options are self explanatory, actually in WoW 9.2.x version it was working 

**Screenshots**
Managed to get find an error through bugsack:
![image](https://user-images.githubusercontent.com/34373753/204087068-5e9ebdec-1130-4a3d-8a55-ab21b39e3c1b.png)

**Error Logs** (not sure this'll help, or if it's exactly what you're looking for - it's what BugSack+BugGrabber picked up, but i have plenty of addons & might actually be conflicting with each other :| ...)

This error is just after cleaning everything + enabling /console option as you mentioned + Reloadui, error is detected as soon as I open the vendor window, nothing else happened in this repro.

29784x Scrap_ElvUI/core.lua:43: attempt to call global 'GetContainerItemID' (a nil value)
[string "@Scrap_ElvUI/core.lua"]:43: in function <Scrap_ElvUI/core.lua:38>
[string "=[C]"]: in function `UpdateSlot'
[string "@ElvUI/Core/Modules/Bags/Bags.lua"]:683: in function `UpdateBagSlots'
[string "@ElvUI/Core/Modules/Bags/Bags.lua"]:399: in function `UpdateAllSlots'
[string "@ElvUI/Core/Modules/Bags/Bags.lua"]:2150: in function `OpenBags'
[string "@ElvUI/Core/Modules/Bags/Bags.lua"]:2072: in function <ElvUI/Core/Modules/Bags/Bags.lua:2058>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ToggleBag'
[string "@FrameXML/ContainerFrame.lua"]:107: in function `ToggleBackpack_Individual'
[string "@FrameXML/ContainerFrame.lua"]:119: in function <FrameXML/ContainerFrame.lua:111>
[string "=[C]"]: in function `ToggleBackpack'
[string "@FrameXML/ContainerFrame.lua"]:290: in function `OpenBackpack'
[string "@FrameXML/ContainerFrame.lua"]:1826: in function <FrameXML/ContainerFrame.lua:1825>
[string "@FrameXML/ContainerFrame.lua"]:1888: in function <FrameXML/ContainerFrame.lua:1859>
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
_ = <table> {
 PickupItem = <function> defined @ElvUI/Core/Modules/Bags/Sort.lua:428
 IsSortIgnored = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:841
 GetBagAssignedInfo = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:872
 BagBar_OnLeave = <function> defined @ElvUI/Core/Modules/Bags/BagBar.lua:33
 ToggleBags = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:2058
 Holder_OnLeave = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:775
 Sort = <function> defined @ElvUI/Core/Modules/Bags/Sort.lua:630
 GetItemQualityColor = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:488
 StartStacking = <function> defined @ElvUI/Core/Modules/Bags/Sort.lua:772
 IsEquipmentSlot = <table> {
 }
 SetDefaultModulePrototype = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 IsEnabled = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 ToggleSortButtonState = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:2098
 Holder_OnClick = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:729
 SortingFadeBags = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:687
 DoMoves = <function> defined @ElvUI/Core/Modules/Bags/Sort.lua:874
 RegisterMessage = <function> defined @ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:88
 UnregisterMessage = <function> defined @ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:151
 TokenFrameWidth = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:1263
 hooks = <table> {
 }
 CommandDecorator = <function> defined @ElvUI/Core/Modules/Bags/Sort.lua:971
 TotalSlotsChanged = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:1112
 UpdateSlot = <function> defined =[C]:-1
 SetEnabledState = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:273
 ProgressQuickVendor = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:2483
 UpdateLayout = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:1137
 Layout = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:923
 BagFrameHidden = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:469
 BagIndice = <table> {
 }
 GetFilterFlagInfo = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:853
 Holder_OnDragStart = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:725
 RegisterUpdateDelayed = <function> defined @ElvUI/Core/Modules/Bags/Sort.lua:787
 FillBags = <function> defined @ElvUI/Core/Modules/Bags/Sort.lua:690
 NewModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 REAGENTBANK_PURCHASED = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:824
 HideItemGlow = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:2226
 GetItemQuestInfo = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:539
 AutoToggle = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:2603
 OpenBags = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:2146
 Initialized = true
 baseName = "ElvUI"
 BagFrame = ElvUI_ContainerFrame {
 }
 REAGENTBANK_SIZE = 98
 BagFrames = <table> {
 }
 SellFrame = ElvUIVendorGraysFrame {
 }
 GetName = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 SearchClear = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:359
 UpdateTokens = <function> defined @ElvUI/Core/Modules/Bags/Bags.lua:1274
 Cooldown_OnHid

**Comment by Mkorny** [comment]
In the meantime I disabled ElvUi and Zygor Vendor-sell, and after 2-3 relogs and switching chars it started working partially. 
(would sell 2-3 BOPs the first time, then not sell again)... after a few more old raids, it just started working normally since...

If you find anything in these logs that might help pinpoint what's exactly conflicting, would save me a LOT of work, but anyway if there's nothing that catches your eye, just go ahead and close it. 

Obrigado pelos mods espectaculares btw... <3 és grande! :)

**Comment by Jaliborc** [comment]
That error comes from Scrap_ElvUI.
Regarding the items not being sold, can you please tell me their item levels and your character level?

**Comment by Jaliborc** [comment]
Also the error log shows me Scrap its out of date... if it persists report again, but I need the above information

**Comment by Mkorny** [comment]
Sorry man didn't have much time to look into it ... it was 100% the conflict i mentioned, the items were low lvl, around cataclysm purple BOP and i was on a max lvl (60)...

Also, it would sell some of them (sometimes) and other time wouldn't even start... but it's sorted :) sorry again i forgot to close it down.
