### ISSUE TITLE
Lua Error When selling

### ISSUE THREAD

**Issue by squish88** [Jaliborc/Scrap#186]
- Addon version: Scrap-10.0.5 for WoW-10.0.2.zip

**Describe the bug** (see LUA below)

I opened the vendor sale screen on my YAK while my character screen was open.  I then right-click sold a helmet from my bag, and got the below LUA error...

Message: Interface/AddOns/Scrap/addons/merchant/learning.lua:45: attempt to index global 'Charsets' (a nil value)
Time: Wed Nov 30 16:47:31 2022
Count: 1
Stack: Interface/AddOns/Scrap/addons/merchant/learning.lua:45: attempt to index global 'Charsets' (a nil value)
[string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:45: in function `OnItemSold'
[string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:28: in function <Interface/AddOns/Scrap/addons/merchant/learning.lua:26>
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 SendMessage = <function> defined @Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 UnregisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 GetDecay = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:79
 RegisterEvent = <function> defined @Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 IsActive = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:75
 OnItemSold = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:41
 OnEnable = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:25
 UnregisterAllEvents = <function> defined @Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 OnItemRefund = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:56
 RegisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 NewModule = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 UnregisterEvent = <function> defined @Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Tag = "SCRAP_"
}
id = 198028
rate = 0.382000
(*temporary) = nil
(*temporary) = 198028
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0.382000
(*temporary) = "Sleet Shined Skullguard"
(*temporary) = "[Sleet Shined Skullguard]"
(*temporary) = "attempt to index global 'Charsets' (a nil value)"
C = <table> {
 hooksecurefunc = <function> defined @Interface/AddOns/Scrap/libs/C_Everywhere/C_Everywhere.lua:37
 rawfind = <function> defined @Interface/AddOns/Scrap/libs/C_Everywhere/C_Everywhere.lua:35
 GetContainerItemPurchaseInfo = <function> defined @Interface/AddOns/Scrap/libs/C_Everywhere/C_Everywhere.lua:45
 locate = <function> defined @Interface/AddOns/Scrap/libs/C_Everywhere/C_Everywhere.lua:36
 GetContainerNumSlots = <function> defined =[C]:-1
 UseContainerItem = <function> defined =[C]:-1
 GetContainerItemID = <function> defined =[C]:-1
 GetContainerItemInfo = <function> defined =[C]:-1
 GetContainerItemQuestInfo = <function> defined @Interface/AddOns/Scrap/libs/C_Everywhere/C_Everywhere.lua:45
}
L = <table> {
 Removed = "Set as useful: %s"
 SoldJunk = "You sold your junk for %s"
 Tutorial_Button = "Scrap will automatically sell all your junk whenever you visit a merchant. But you can manually sell it: simply Left-Click on the Scrap button.

Right-Click on the button to bring extra options."
 AutoRepair = "Automatically Repair"
 DestroyWorthless = "Destroy Worthless"
 SafeMode = "Safe Mode"
 LowConsume = "Low Consumables"
 Junk = "Junk"
 Tutorial_Drag = "What if you want to tell Scrap which items to sell or not? Simply Drag it

**Comment by Jaliborc** [comment]
👍🏻
