### ISSUE TITLE
You can not buy back items if 'intelligent learning' is activated

### ISSUE THREAD

**Issue by erendur81** [Jaliborc/Scrap#187]
- Addon version: 10.0.5
 - Server patch: 10.0.2

**Describe the bug**
I am not able to buy by error sold items back if intelligent learning is activated.
No error

Steps to reproduce the behaviour:
1. Activate intelligent learning in the settings of the addon
2. Sell an item to a vendor
3. Try to buy it back from the vendor

**Expected behaviour**
I should be able to buy my items back

**Error Logs**
56x Scrap/addons/merchant/learning.lua:59: attempt to index global 'Charsets' (a nil value)
[string "@Scrap/addons/merchant/learning.lua"]:59: in function `OnItemRefund'
[string "@Scrap/addons/merchant/learning.lua"]:35: in function `BuybackItem'
[string "*MerchantFrame.xml:393_OnClick"]:1: in function <[string "*MerchantFrame.xml:393_OnClick"]:1>

Locals:
self = <table> {
 SendSignal = <function> defined @Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 SendMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 UnregisterSignal = <function> defined @Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 GetDecay = <function> defined @Scrap/addons/merchant/learning.lua:79
 RegisterEvent = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 IsActive = <function> defined @Scrap/addons/merchant/learning.lua:75
 OnItemSold = <function> defined @Scrap/addons/merchant/learning.lua:41
 OnEnable = <function> defined @Scrap/addons/merchant/learning.lua:25
 UnregisterAllEvents = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 OnItemRefund = <function> defined @Scrap/addons/merchant/learning.lua:56
 RegisterSignal = <function> defined @Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 NewModule = <function> defined @Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:68

**Comment by Jaliborc** [comment]
👍🏻
