### ISSUE TITLE
8.0.1 Error: Binding header SCRAP

### ISSUE THREAD

**Issue by nancikennedy** [Jaliborc/Scrap#19]
3x Binding header SCRAP is defined more than once in Scrap\Bindings.xml

**Comment by Daeveren** [comment]
Someone offered a fix on another website:

Go to Bindings.xml in the same folder. Remove the second "header="SCRAP"" from the <Binding> tag for SCRAP_TOGGLE. Only one header definition is valid, which should be defined with the first binding (SCRAP_SELL).
	

> <Binding name="SCRAP_TOGGLE" category="ADDONS">

 ^ This is how it should look.

**Comment by nancikennedy** [comment]
Thanks. :)

**Comment by Jaliborc** [comment]
You dont have the latest (today's version). I fixed these very same issues a few hours ago.
