### ISSUE TITLE
Feature request: do not auto sell gray BOEs

### ISSUE THREAD

**Issue by KyrosKrane** [Jaliborc/Scrap#193]
**Is your feature request related to a problem? Please describe.**
With 10.0.5, gray items are now transmoggable. Scrap still auto sells them, which can lead to the loss of transmogs or sellable items.

**Describe the solution you'd like**
1) Add a new option to Scrap to not sell equippable, poor-quality (gray), BOE items. Non-equippable items, BOP gray items, and non-binding equippable gray items can continue to be sold.

2) Add a second option to auto-vendor items kept by option 1 if you already know the appearance and appearance source of that item. (Blizzard tracks two entries for transmogs: the appearance of the item, and the source of that appearance. It's possible to have a specific appearance, but when you search for that appearance by the name of the item, it won't appear, because you learned that appearance from some other source item with an identical appearance but different name.)

The manual keep and vendor lists should still override the options above. That is, if I mark an item as vendorable, it should still be sold if it meets the criteria of 1; and if I mark an item as always keep, it should always be kept even though it qualifies for 2.

It's also possible to just add 1, and let the user manage 2 by marking each item as vendorable when the appearance/source is learned.

**Describe alternatives you've considered**
In practice, Blizzard's changes mean I have to manually manage selling gray items to a vendor. I've turned on the Scrap option to sell 10 at a time, and I review each group of sales to see if it included any BOEs, then I manually buy them back and either mark them excluded or learn them right away. I also have to be super careful when randomly visiting a vendor with gray items in my bags, which can lead to mogs being sold unintentionally.

**Additional context**
Thanks in advance!

**Comment by Ketrel** [comment]
I added this in my copy.

in 

`addons/main/main.lua`  

Line 129: Change   
    `    local _, link, quality, level,_,_,_,_, slot, _, value, class, subclass = GetItemInfo(id)`  
    to  
    `    local _, link, quality, level,_,_,_,_, slot, _, value, class, subclass, bindType = GetItemInfo(id)`  

Line 137: Change
    `            if quality == POOR then`  
    to  
    `            if quality == POOR and bindType ~= LE_ITEM_BIND_ON_EQUIP then`

Line 146  
    `    elseif quality == POOR then`  
    to  
    `    elseif quality == POOR and bindType ~= LE_ITEM_BIND_ON_EQUIP then`

**Comment by Ketrel** [comment]
Quick followup to my tweak

if you change my instances of

`bindType ~= LE_ITEM_BIND_ON_EQUIP`

to 

`(bindType ~= LE_ITEM_BIND_ON_EQUIP or IsBound(location) == true)`

It should sell grey BoEs IF they're already soulbound (like ones you equipped or those legion ones)

**Comment by R-Adrian** [comment]
beware that v10.0.11 of Scrap was pushed today on Curseforge without any changes about gray BoE transmogs (i.e. it still tries to sell them)... if you patched the files locally then you'll have to re-apply the changes.

**Comment by ZehelFenris** [comment]
I would point out that the lines you need to change are the lines 153, 161 and 170 in the current version of the addon

**Comment by Araldwenn** [comment]
I also would like this to be implemented.

**Comment by Mirades** [comment]
> I added this in my copy.
> 
> in
> 
> `addons/main/main.lua`
> 
> Line 129: Change ` local _, link, quality, level,_,_,_,_, slot, _, value, class, subclass = GetItemInfo(id)` to ` local _, link, quality, level,_,_,_,_, slot, _, value, class, subclass, bindType = GetItemInfo(id)`
> 
> Line 137: Change ` if quality == POOR then` to ` if quality == POOR and bindType ~= LE_ITEM_BIND_ON_EQUIP then`
> 
> Line 146 ` elseif quality == POOR then` to ` elseif quality == POOR and bindType ~= LE_ITEM_BIND_ON_EQUIP then`
> 
> Those were the only two places I could find where it actually queries game data for the quality, so adding the additional condition for the bind type should make it not sell grey boes.

i have tried this (obviously didn't go for the lines on the new version, but searched for the correct lines)
however now the addon just doesn't do anything anymore, doesn't work at all :/
any new workaround/fix?

**Comment by Jaliborc** [comment]
> I added this in my copy.
> 
> in
> 
> `addons/main/main.lua`
> 
> Line 129: Change ` local _, link, quality, level,_,_,_,_, slot, _, value, class, subclass = GetItemInfo(id)` to ` local _, link, quality, level,_,_,_,_, slot, _, value, class, subclass, bindType = GetItemInfo(id)`
> 
> Line 137: Change ` if quality == POOR then` to ` if quality == POOR and bindType ~= LE_ITEM_BIND_ON_EQUIP then`
> 
> Line 146 ` elseif quality == POOR then` to ` elseif quality == POOR and bindType ~= LE_ITEM_BIND_ON_EQUIP then`
> 
> Those were the only two places I could find where it actually queries game data for the quality, so adding the additional condition for the bind type should make it not sell grey boes.

Added in new version! Thank you for the community implementation, it's hard to get to all the requests!

**Comment by Jaliborc** [comment]
For clarification: version comes tomorrow or the fay after.
