### ISSUE TITLE
Please tag "COSMETIC" items as valuable.

### ISSUE THREAD

**Issue by CXWRTH** [Jaliborc/Scrap#197]
**Please list the names of the items in question**
Things like:
[Selfless Wings of the Ascended](https://www.wowhead.com/item=181295/selfless-wings-of-the-ascended)
[Dragon Dinner Fork](https://www.wowhead.com/item=199648/dragon-dinner-fork)

**List the numeric identifiers of the items**
I'm not sure what the item type for **cosmetic** is. It should just be the whole category.

**Describe why the items should be excluded**
They are cosmetics!?
If you want to get fancy cosmetics that have already been learned are eligible for scrap, but it's scrapping all cosmetics, learned or not. Thankfully 12 sales protection lets me pull them back right now.

**Comment by Jaliborc** [comment]
Added!
