### ISSUE TITLE
Spotlight Junk Coin Icons Not Working While Bagnon Installed

### ISSUE THREAD

**Issue by entyoun** [Jaliborc/Scrap#198]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.10 and Bagnon 10.0.16
 - Server patch: 10.0.7.48966

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
When both Bagnon and Scrap are installed, the coin icon item overlay for items labeled as Junk does not display. The coin icon works if Bagnon is disabled. I have tried disabling the poor item icon in Bagnon, and it still does not work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install both Bagnon and Scrap
2. Mark anything as junk in Scrap
3. Try to turn on Junk Coin Icon in Scrap settings
4. Observe that there is no icon when Bagnon is enabled

**Expected behaviour**
Item icons should have a junk coin icon on them when both Bagnon and Scrap are installed.

**Screenshots**
With Bagnon enabled:
![image](https://user-images.githubusercontent.com/50379525/230532196-7ae7f82a-6b6e-40c1-85cc-61106d274acc.png)

Without Bagnon enabled:
![image](https://user-images.githubusercontent.com/50379525/230532877-448a3db5-b044-408c-b6fc-246dab2a4f6d.png)

**Error Logs**
No errors with the console variable enabled

**Additional context**
Bagnon's poor icons seem to work just fine, so maybe we could borrow some code from there? :)

**Comment by Jaliborc** [comment]
Install Bagnon Scrap
