### ISSUE TITLE
8.0.1 Error: Loading Tests.lua

### ISSUE THREAD

**Issue by nancikennedy** [Jaliborc/Scrap#20]
5x Error loading Scrap\Tests.lua

**Comment by Daeveren** [comment]
Edit Scrap.toc file and put a # sign at the start of the line with tests.lua

**Comment by nancikennedy** [comment]
More groaning lol, and more thanks

**Comment by Jaliborc** [comment]
You dont have the latest (today's version). I fixed these very same issues a few hours ago.

**Comment by Mythris29** [comment]
@Jaliborc Just installed 13.8 and this error is happing right after logging in

202x Error loading Scrap\Tests.lua
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>
