### ISSUE TITLE
Hundreds of errors since latest patch

### ISSUE THREAD

**Issue by Grizz2202** [Jaliborc/Scrap#200]
I have 200+ errors of "254x Scrap/addons/main/sellPrices.lua:55: attempt to call global 'GetContainerItemInfo' (a nil value)" since i updated. 

Did i do something wrong?

**Comment by Starlynk1** [comment]
Getting errors with the sellPrices.lua as well
`166x Interface\AddOns\Scrap\addons\main\sellPrices.lua:43: attempt to compare number with nil
[string "@Interface\AddOns\Scrap\addons\main\sellPrices.lua"]:43: in function `AddLine'
[string "@Interface\AddOns\Scrap\addons\main\sellPrices.lua"]:92: in function <Interface\AddOns\Scrap\addons\main\sellPrices.lua:91>
[string "=[C]"]: in function `SetHyperlink'
[string "@Interface\AddOns\FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0-101090.lua"]:1246: in function `GetPoleType'
[string "@Interface\AddOns\FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0-101090.lua"]:1304: in function <...\FishingBuddy\Libs\LibFishing-1.0\LibFishing-1.0.lua:1295>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\FishingBuddy\FishingBuddy-0.8.3.lua"]:565: in function <Interface\AddOns\FishingBuddy\FishingBuddy.lua:561>
[string "@Interface\AddOns\FishingBuddy\FishingBuddy-0.8.3.lua"]:1000: in function <Interface\AddOns\FishingBuddy\FishingBuddy.lua:999>
[string "@Interface\AddOns\FishingBuddy\FishingBuddy-0.8.3.lua"]:1406: in function <Interface\AddOns\FishingBuddy\FishingBuddy.lua:1273>

Locals:
self = <table> {
 SendSignal = <function> defined @Interface\AddOns\Scrap\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 OnMail = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:74
 OnBag = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:54
 RegisterMessage = <function> defined @Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143
 OnQuest = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:65
 AddLine = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:40
 OnSetCraftItem = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:87
 SendMessage = <function> defined @Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:49
 UnregisterSignal = <function> defined @Interface\AddOns\Scrap\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 RegisterEvent = <function> defined @Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:164
 OnInventory = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:59
 OnLink = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:91
 OnSetTradeSkillItem = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:79
 OnEnable = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:24
 OnLoot = <function> defined @Interface\AddOns\Scrap\addons\main\sellPrices.lua:70
 UnregisterAllEvents = <function> defined @Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:164
 RegisterSignal = <function> defined @Interface\AddOns\Scrap\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 NewModule = <function> defined @Interface\AddOns\Scrap\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 UnregisterEvent = <function> defined @Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143
 Tag = "SCRAP_"
}
tip = FishLibTooltip {
 SetBorderBlendMode = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:203
 NineSlice = <unnamed> {
 }
 0 = <userdata>
 updateTooltip = 0.200000
 TooltipBackdropOnLoad = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:172
 TopOverlay = <unnamed> {
 }
 GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:191
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:199
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 SetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:187
 layoutType = "TooltipDefaultLayout"
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:195
}
item = "item:6256"
count = nil
silent = nil
price = nil
(*temporary) = 11
(*temporary) = <function> defined =[C]:-1
(*temporary) = "item:6256"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
`

**Comment by MyTechnoHunter** [comment]
> I have 200+ errors of "254x Scrap/addons/main/sellPrices.lua:55: attempt to call global 'GetContainerItemInfo' (a nil value)" since i updated.
> 
> Did i do something wrong?

no, you didn't, to fix it do the following

goto your file listed in the error (for your game version, either the _retail_ or _classic_ folder)

at the top of the file right under the `if TooltipDataProcessor then return end`
add the following `local C = LibStub('C_Everywhere').Container`

it should look like so
`if TooltipDataProcessor then return end`
`local C = LibStub('C_Everywhere').Container`

then goto the line 55 (now line 56) and replace 

`function Prices.OnBag(tip, bag, slot)`
`    local _, count, _,_,_,_,_,_,_, id = GetContainerItemInfo(bag, slot)`
`    Prices:AddLine(tip, id, count, true)`
`end`

with the following

`function Prices.OnBag(tip, bag, slot)`
`    local info = C.GetContainerItemInfo(bag, slot)`
`    local id = info.itemID`
`    local count = info.stackCount`
`    Prices:AddLine(tip, id, count, true)`
`end`

save your file and /reload in game

**Comment by Starlynk1** [comment]
That didn't fix anything, still errors out

**Comment by Lysandro** [comment]
Surround it with a "if then" clause than it looks better:

```
function Prices.OnBag(tip, bag, slot)
    local info = C.GetContainerItemInfo(bag, slot)
	if info then
		local id = info.itemID
		local count = info.stackCount
		Prices:AddLine(tip, id, count, true)
	end
end
```

**Comment by Starlynk1** [comment]
What I found with my issue was that the function...
```
function Prices:AddLine(tip, item, count, silent)
    if item and (not silent or not self.shopping) and Scrap.sets.prices and not tip:IsForbidden() then
        local price = select(11, GetItemInfo(item))
        if price > 0 then
            tip.__hasPrice = true
            tip:AddLine(GetCoinTextureString(price * (count or 1)), 1,1,1)
            tip:Show()
        end
    end
end 
```
was also picking up items without prices. I changed the if statement and it appears to have gotten rid of the error (Lines 41-50)
```
function Prices:AddLine(tip, item, count, silent)
    if item and (not silent or not self.shopping) and Scrap.sets.prices and not tip:IsForbidden() then
        local price = select(11, GetItemInfo(item))
        if price then
            tip.__hasPrice = true
            tip:AddLine(GetCoinTextureString(price * (count or 1)), 1,1,1)
            tip:Show()
        end
    end
end 
```
