### ISSUE TITLE
Attempt to call global 'GetContainerItemInfo' (a nil value)

### ISSUE THREAD

**Issue by Spotnick2** [Jaliborc/Scrap#201]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.11

**Describe the bug**
 
The update today on WOTLK Classic does this non-stop multiple times, potential issue with TSM?

61x Scrap/addons/main/sellPrices.lua:55: attempt to call global 'GetContainerItemInfo' (a nil value)
[string "@Scrap/addons/main/sellPrices.lua"]:55: in function <Scrap/addons/main/sellPrices.lua:54>
[string "=[C]"]: in function `SetBagItem'
[string "@TradeSkillMaster/LibTSM/Service/TooltipScanning.lua"]:158: in function `SetContainerItem'
[string "@TradeSkillMaster/LibTSM/Service/TooltipScanning.lua"]:32: in function `IsSoulbound'
[string "@TradeSkillMaster/LibTSM/Service/InventoryInfo.lua"]:79: in function `IsSoulbound'
[string "@TradeSkillMaster/LibTSM/Service/BagTracking.lua"]:619: in function `ScanBagSlot'
[string "@TradeSkillMaster/LibTSM/Service/BagTracking.lua"]:545: in function `ScanBagOrBank'
[string "@TradeSkillMaster/LibTSM/Service/BagTracking.lua"]:438: in function `BagUpdateDelayedHandler'
[string "@TradeSkillMaster/LibTSM/Service/BagTracking.lua"]:205: in function `gameDataLoadFunc'
[string "@TradeSkillMaster/LibTSM/Core.lua"]:175: in function `ProcessGameDataLoad'
[string "@TradeSkillMaster/LibTSM/Core.lua"]:220: in function <TradeSkillMaster/LibTSM/Core.lua:202>

Locals:
tip = TSMScanTooltip {
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:203
 NineSlice = Frame {
 }
 updateTooltip = 0.200000
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:172
 0 = <userdata>
 TopOverlay = Texture {
 }
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:191
 GetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:199
 needsReset = true
 BottomOverlay = Texture {
 }
 SetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:187
 layoutType = "TooltipDefaultLayout"
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:195
}
bag = 0
slot = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = "attempt to call global 'GetContainerItemInfo' (a nil value)"
Prices = <table> {
 SendSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 OnMail = <function> defined @Scrap/addons/main/sellPrices.lua:74
 OnBag = <function> defined @Scrap/addons/main/sellPrices.lua:54
 RegisterMessage = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 OnQuest = <function> defined @Scrap/addons/main/sellPrices.lua:65
 AddLine = <function> defined @Scrap/addons/main/sellPrices.lua:40
 OnSetCraftItem = <function> defined @Scrap/addons/main/sellPrices.lua:87
 SendMessage = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:54
 UnregisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 RegisterEvent = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterAllMessages = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 OnInventory = <function> defined @Scrap/addons/main/sellPrices.lua:59
 OnLink = <function> defined @Scrap/addons/main/sellPrices.lua:91
 OnSetTradeSkillItem = <function> defined @Scrap/addons/main/sellPrices.lua:79
 OnEnable = <function> defined @Scrap/addons/main/sellPrices.lua:24
 OnLoot = <function> defined @Scrap/addons/main/sellPrices.lua:70
 UnregisterAllEvents = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 RegisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 NewModule = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 UnregisterEvent = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 Tag = "SCRAP_"
}

**Comment by MyTechnoHunter** [comment]
nope, problem exists in the file listed at the top of the stack (sellPrices.lua)
fix linked in https://github.com/Jaliborc/Scrap/issues/200 till its updated..
