### ISSUE TITLE
I have no idea what's causing it. 

### ISSUE THREAD

**Issue by supert0kern** [Jaliborc/Scrap#202]
"Select all and Copy the above error message to report this bug."

And here it is:

Date: 2023-05-02 22:49:40
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Scrap/addons/main/sellPrices.lua line 55:
   attempt to call global 'GetContainerItemInfo' (a nil value)
Debug:
   [string "=[C]"]: GetContainerItemInfo()
   [string "@Interface/AddOns/Scrap/addons/main/sellPrices.lua"]:55:
      Interface/AddOns/Scrap/addons/main/sellPrices.lua:54
   [string "=[C]"]: SetBagItem()
   [string "@Interface/AddOns/Auc-Advanced/CorePost.lua"]:602: IsAuctionable()
   [string "@Interface/AddOns/Auc-Advanced/Modules/Auc-Util-ItemSuggest/Auc-Util-ItemSuggest.lua"]:404: suggestor()
   [string "@Interface/AddOns/Auc-Advanced/Modules/Auc-Util-ItemSuggest/Auc-Util-ItemSuggest.lua"]:93: Suggest()
   [string "@Interface/AddOns/Auc-Advanced/Modules/Auc-Util-ItemSuggest/Auc-Util-ItemSuggest.lua"]:1073:
      ...odules/Auc-Util-ItemSuggest/Auc-Util-ItemSuggest.lua:1070
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Auc-Advanced/CoreUtil.lua"]:895: SendProcessorMessage()
   [string "@Interface/AddOns/Auc-Advanced/CoreMain.lua"]:183:
      Interface/AddOns/Auc-Advanced/CoreMain.lua:60
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:129:
      ...AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua:113
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:189: h()
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:500: OnTooltipSetItem()
   [string "@Interface/AddOns/Enchantrix/EnxMain.lua"]:240:
      Interface/AddOns/Enchantrix/EnxMain.lua:236
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:428: SetBagItem()
   [string "@Interface/FrameXML/ContainerFrame_Shared.lua"]:1362:
      Interface/FrameXML/ContainerFrame_Shared.lua:1333
   [string "=[C]"]: ContainerFrameItemButton_OnEnter()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:359: ShowTooltip()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:186:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:182
Locals:

AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucScanData, v3.4.6908 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Auctionator, v10.1.0
  BagBrother, v
  Bagnon, v10.0.16
  BeanCounter, v3.4.6933 (SwimmingSeadragon)
  DBMCore, v5249a11
  DBMStatusBarTimers, v5249a11
  DBMVPVEM, v1691239
  Decursive, v2.7.9.1
  Details, v#Details.DF.Wrath.10.0.7.10737.148
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6942 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  FasterLoot, v10.1.0
  FasterLootVanilla, vVanilla-1.14.3
  FasterLootWrath, vWOTLK-3.4.1
  Informant, v3.4.6934 (SwimmingSeadragon)
  LeatrixMaps, v3.0.129
  LeatrixPlus, v3.0.129
  LeatrixSounds, v3.0.129
  Mapster, v1.10.7
  Questie, v8.1.1
  RareScanner, v3.4.1.1
  Scrap, v10.0.11
  ScrapMerchant, v
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  SpellActivationOverlay, v0.9.0
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TomTom, vv3.3.8-release
  WeakAuras, v5.5.1
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=5aa)

**Comment by Starlynk1** [comment]
Check issue 200, fix in there
