### ISSUE TITLE
Scrap Addon Lua Error

### ISSUE THREAD

**Issue by Feronas** [Jaliborc/Scrap#203]
Hello, been getting this error as of today from scrap addon on WoW Classic Wrath of the Lich King

![image](https://user-images.githubusercontent.com/65334149/235890208-f627082e-9921-465c-a383-0b058db51d9c.png)

Addon version
![image](https://user-images.githubusercontent.com/65334149/235890272-bf787dbc-f789-4a26-83a7-4ec2b935b763.png)

**Comment by Amaceika** [comment]
Getting the same error any fix for it?

**Comment by trankvillion** [comment]
так что ни кто так и не помог с проблемой?
