### ISSUE TITLE
LUA error in 10.1.5

### ISSUE THREAD

**Issue by Dmeister406** [Jaliborc/Scrap#209]
**Running Software (issues missing this information will be deleted):**
 - Addon version:10.1
 - Server patch: 50401

 **Have you read the changelog? (please don't waste our time)**
 Yes.

**Describe the bug**
Right click on repair vendor, auto repairs and generates the LUA error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to repair vendor
2. Right click on repair vendor to auto repair items.

**Expected behaviour**
Expect no LUA error to appear.

**Screenshots**
N/A

**Error Logs**
18x Scrap/addons/merchant/button.lua:166: attempt to index global 'MerchantRepairText' (a nil value)
[string "@Scrap/addons/merchant/button.lua"]:166: in function `UpdatePosition'
[string "@Scrap/addons/merchant/button.lua"]:74: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BagBrother/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Scrap/addons/main/main.lua"]:47: in function <Scrap/addons/main/main.lua:47>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = Button {
 0 = <userdata>
 OnEnter = <function> defined @Scrap/addons/merchant/button.lua:129
 UnregisterAllEvents = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 OnReceiveDrag = <function> defined @Scrap/addons/merchant/button.lua:121
 Delaying = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:46
 UpdateState = <function> defined @Scrap/addons/merchant/button.lua:143
 OnMerchant = <function> defined @Scrap/addons/merchant/button.lua:59
 UpdatePosition = <function> defined @Scrap/addons/merchant/button.lua:149
 OnClose = <function> defined @Scrap/addons/merchant/button.lua:86
 Sell = <function> defined @Scrap/addons/merchant/button.lua:191
 Delay = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 Tag = "SCRAP_"
 OnBagUpdate = <function> defined @Scrap/addons/merchant/button.lua:78
 AnyJunk = <function> defined @Scrap/addons/merchant/button.lua:238
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 border = Texture {
 }
 GetReport = <function> defined @Scrap/addons/merchant/button.lua:223
 UpdateTip = <function> defined @Scrap/addons/merchant/button.lua:169
 SendMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 CanGuildRepair = <function> defined @Scrap/addons/merchant/button.lua:253
 UnregisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 RegisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 background = Texture {
 }
 icon = Texture {
 }
 SendSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 OnEnable = <function> defined @Scrap/addons/merchant/button.lua:25
 OnLeave = <function> defined @Scrap/addons/merchant/button.lua:134
 NewModule = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 Repair = <function> defined @Scrap/addons/merchant/button.lua:242
 OnClick = <function> defined @Scrap/addons/merchant/button.lua:94
 UnregisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 RegisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1.100000
(*temporary) = <userdata>
(*temporary) = "LEFT"
(*temporary) = -17
(*temporary) = 0.500000
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = "attempt to index global 'MerchantRepairText' (a nil value)"

**Additional context**
N/A

**Comment by speedwaystar** [comment]
resolved by commenting out line 166 of addoins/merchant/buttons.lua thus:

`	--MerchantRepairText:Hide()`

**Comment by Dmeister406** [comment]
Thanks heaps for that! Will give it a go.

**Comment by megasquid** [comment]
> resolved by commenting out line 166 of /addons/merchant/buttons.lua thus:
> 
> ` --MerchantRepairText:Hide()`

This resolved the issue for me.
