### ISSUE TITLE
8.0.1 Error: Loading WoWTest-1.0.lua

### ISSUE THREAD

**Issue by nancikennedy** [Jaliborc/Scrap#21]
5x Error loading Scrap\Libs\WoWTest-1.0\WoWTest-1.0.lua

p.s. I like to make separate tickets for each issue for clarity, etc. If you would prefer them all in one ticket, please let me know and I will adjust accordingly. :)

**Comment by Daeveren** [comment]
Edit Scrap.toc file and put a # sign at the start of the line with WoWTest-1.0.lua

**Comment by nancikennedy** [comment]
I saw this and groaned...thanks :)

**Comment by Jaliborc** [comment]
You dont have the latest (today's version). I fixed these very same issues a few hours ago.
