### ISSUE TITLE
Constant errors

### ISSUE THREAD

**Issue by ChloeMarie** [Jaliborc/Scrap#210]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.1
 - Server patch: 10.1.5.50401

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. X

**Describe the bug**
I opened a vendor, had an error, and every time I sold an item there was another error message.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to vendor
2. Click on vendor
3. See error
4. Sell item to vendor
5. See another error
6. Continue to see errors each time an item is sold

**Expected behaviour**
Sell items with no errors
**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

30x Scrap/addons/merchant/button.lua:166: attempt to index global 'MerchantRepairText' (a nil value)
[string "@Scrap/addons/merchant/button.lua"]:166: in function `UpdatePosition'
[string "@Scrap/addons/merchant/button.lua"]:74: in function `?'
[string "@BagSync/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BagSync/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BagSync/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Scrap/addons/main/main.lua"]:47: in function <Scrap/addons/main/main.lua:47>
[string "=[C]"]: ?
[string "@BagSync/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BagSync/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BagSync/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ceBagSync/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = Button {
 0 = <userdata>
 OnEnter = <function> defined @Scrap/addons/merchant/button.lua:129
 UnregisterAllEvents = <function> defined @BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 OnReceiveDrag = <function> defined @Scrap/addons/merchant/button.lua:121
 Delaying = <function> defined @PetTracker/libs/MutexDelay-1.0/MutexDelay-1.0.lua:46
 UpdateState = <function> defined @Scrap/addons/merchant/button.lua:143
 OnMerchant = <function> defined @Scrap/addons/merchant/button.lua:59
 UpdatePosition = <function> defined @Scrap/addons/merchant/button.lua:149
 OnClose = <function> defined @Scrap/addons/merchant/button.lua:86
 Sell = <function> defined @Scrap/addons/merchant/button.lua:191
 Delay = <function> defined @PetTracker/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 Tag = "SCRAP_"
 OnBagUpdate = <function> defined @Scrap/addons/merchant/button.lua:78
 AnyJunk = <function> defined @Scrap/addons/merchant/button.lua:238
 RegisterMessage = <function> defined @BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 border = Texture {
 }
 GetReport = <function> defined @Scrap/addons/merchant/button.lua:223
 UpdateTip = <function> defined @Scrap/addons/merchant/button.lua:169
 SendMessage = <function> defined @BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 CanGuildRepair = <function> defined @Scrap/addons/merchant/button.lua:253
 UnregisterSignal = <function> defined @PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 RegisterSignal = <function> defined @PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 background = Texture {
 }
 icon = Texture {
 }
 SendSignal = <function> defined @PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 OnEnable = <function> defined @Scrap/addons/merchant/button.lua:25
 OnLeave = <function> defined @Scrap/addons/merchant/button.lua:134
 NewModule = <function> defined @PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 Repair = <function> defined @Scrap/addons/merchant/button.lua:242
 OnClick = <function> defined @Scrap/addons/merchant/button.lua:94
 UnregisterEvent = <function> defined @BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 RegisterEvent = <function> defined @BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = Button {
 0 = <userdata>
 OnEnter = <function> defined @Scrap/addons/merchant/button.lua:129
 UnregisterAllEvents = <function> defined @BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 OnReceiveDrag = <function> defined @Scrap/addons/merchant/button.lua:121
 Delaying = <function> defined @PetTracker/libs/MutexDelay-1.0/MutexDelay-1.0.lua:46
 UpdateState = <function> defined @Scrap/addons/merchant/button.lua:143
 OnMerchant = <function> defined @Scrap/addons/merchant/button.lua:59
 UpdatePosition = <function> defined @Scrap/addons/merchant/button.lua:149
 OnClose = <function> defined @Scrap/addons/merchant/button.lua:86
 Sell = <function> defined @Scrap/addons/merchant/button.lua:191
 Delay = <function> defined @PetTracker/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 Tag = "SCRAP_"
 OnBagUpdate = <function> defined @Scrap/addons/merchant/butto

**Additional context**

**Comment by Kirri777** [comment]
#209 Duplicated

**Comment by wheatbread** [comment]
See https://github.com/Jaliborc/Scrap/issues/209#issuecomment-1632360934 for fix

**Comment by pattyland** [comment]
It hate doing this is PR Discussion but it seems fitting (again): https://discord.com/channels/1044414761573564466/1044414762840240204/1126580170250264659
