### ISSUE TITLE
Scrap version 10.1.1 still always sells gray unknown appearance BOE transmogs 

### ISSUE THREAD

**Issue by R-Adrian** [Jaliborc/Scrap#215]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Scrap 10.1.1 / Curseforge - july 19th 2023
 - Server patch: Retail 10.1.5 (50504) - July 17th 2023 build by Blizzard

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. - yes, i read it.

**Describe the bug**
v10.1.1 changelog says (among others):
- Dragonflight: Cosmetic items are now not considered junk by default.
- All: Marked multiple items to be not junk by default given community feedback.

but v10.1.1 of Scrap still actually sells all gray BOE transmogs irrespective of their soulbound/not soulbound or known / not known appearance

**To Reproduce**
Steps to reproduce the behaviour:

1. Have the "CanIMogIt?" addon installed so you can see very quickly from their overlay icon if a certain item is known as transmog or not.
2.  If you have multiple alts make sure to log on all of them too so that CanIMogIt can update its internal transmog database with all known transmogs across all alts - when hopping between alts wait for CIMI to finish scanning / updating the database before logging out. The Blizzard transmog API tends to sometimes skip over appearances for alts.

Note: the "CanIMogIt?" addon is optional but it helps A LOT with visually locating unknown transmogs in bags + AH at next steps.

3. Go to the Auction House on any character
4. look at either weapons or armour categories, sort by price

5. buy the cheapest gray item usable by your current character class that is not already known as transmog (probably this will cost just a few silver coins)
6. do not pick up the mail yet...
7. buy the cheapest gray item that is equippable by your current character class, but not known as transmog and NOT LEARNABLE as transmog by your current character, (but is learnable by alts)
8. buy the cheapest gray item that is NOT usable by your current character class, but is usable by an alt, and that item is not already known as transmog - the CanIMogIt addon helps a lot in this case by placing icons in the AH for the item transmog known/not known state.

9. go now to pick up those items from the mailbox
10. result 1: they all end up in bags with a Scrap gold coin on them...
11. go to a vendor.. press the "sell junk" button
12. result 2: the Scrap addon will attempt to learn / sell-to-vendor all those items, but it actually trashes the transmog appearances from those the current character cannot learn. 

**Example: **
On a hunter class character i bought in AH the following items with transmog appearances not already known:
- Balanced Long Bow  (gray bow)
- Sooty Mail Shoulderpads (gray mail shoulders)
- Frozen Belt (gray leather belt)
- Bleached Plate Gloves (gray plate gloves)
(all of them were less than 1G in total on my realm)

result:
- the bow and shoulders became soulbound, appearances were learned and the items were vendored. (correct so far)
- the leather belt and plate gloves, even if they remained BOEs - they were scrapped / vendored as well, even if they are useful for learning as transmogs on my alts.

**Expected behaviour**
Do not sell gray BOEs with appearances that are not known and not learnable by current character (but are learnable by alts).
(or at least a checkbox for this in the addon options window)

**Screenshots**
not applicable

**Error Logs**
this is a logical item scrapping error, not a LUA error - not possible to get logs for this.

**Comment by Ouroboratika** [comment]
Just want to +1 this. Not the end of the world, but a little bit of a pain to have to disable auto-sell so I don't accidentally sell and forget some grey transmogs that I intend to email to alts. I'd understand if considering what transmogs I have unlocked is outside of the scope of this addon, but I would definitely appreciate even a "Don't sell equipment" checkbox; I wouldn't mind manually selling equipment manually as long as the rest of my junk items could be sold automatically again.

**Comment by olioster** [comment]
Yeah, it's disappointing that it still sells unlearned grey items.

**Comment by Ketrel** [comment]
I'm forking it to make a pull request to fix it.  If it doesn't get merged, I'll try to keep my fork rebased as necessary.

**Comment by R-Adrian** [comment]
i don'r think forking would be even useful... by now it's painfully obvious that the GitHub "source" for this addon is only an afterthought - there have been updates published on CurseForge without any commits to the code here - thus my conclusion about the GitHub code.

also, since there is no license published, forking this addon is technically illegal even if github allows it...
the .TOC file that is published on CurseForge even spells it out clearly... this addon is "`## X-License: All Rights Reserved`" according to the TOC file, thus any fork is illegal.

**Comment by Ouroboratika** [comment]
I decided to just poke around the code (not of this repo but of just what I have downloaded from Curse, since R-Adrian mentioned that this repo doesn't seem to be up to date) and I went to `Scrap/addons/main/main.lua`. In the `IsFiltered` function I've adjusted the logic to simplify the armor and weapon section like so:
```elseif class == ARMOR or class == WEAPON then
		if value and slot ~= 'INVTYPE_TABARD' and slot ~= 'INVTYPE_BODY' and subclass ~= FISHING_POLE then
			if quality == POOR then
				return (slot ~= 'INVTYPE_SHOULDER' and level > INTRO_BREAKPOINT) or level > SHOULDER_BREAKPOINT
			elseif quality >= UNCOMMON and quality <= EPIC and location and C_Item.IsBound(location) then
				if IsEquippableItem(id) and not Search:BelongsToSet(id) then
					return self:IsLowEquip(slot, level) or self.charsets.unusable and Search:IsUnusable(id)
				end
			end
		end```
to
```elseif class == ARMOR or class == WEAPON then
    return false
```
and that did the trick as far as just not auto-selling weapons and armor.

**Comment by Ketrel** [comment]
Original 

> i don't think forking would be even useful... by now it's painfully obvious that the GitHub "source" for this addon is only an afterthought - there have been updates published on CurseForge without any commits to the code here - thus my conclusion about the GitHub source.
> 
> also, since there is no license published, forking this addon is technically illegal even if github allows it... the .TOC file that is published on CurseForge even spells it out clearly... this addon is "`## X-License: All Rights Reserved`" according to the TOC file, thus any fork is illegal.

The original version (still available on Curse) has a license.url that links to GPL3

I did a quick search of the repo, I can see references in commits to GPL3 as well https://github.com/Jaliborc/Scrap/commit/57aad70990317da29f6459b0a8418010c6656d33#diff-18c6b16d60525286bde9b79e86ccef403d8eafac1865a88142093fa0cb46c48d

I'm not sure if something got reset to default, but it can be forked at the very least from the latest point that was released under GPL3

**Comment by R-Adrian** [comment]
update: this looks to be pretty much solved by https://github.com/Jaliborc/Scrap/commit/f71222323a35156ef80cf443b21fe091189b0c69 

that commit does not consider the known/not known state of the item appearance but it stops selling BOEs at least, thank you!
