### ISSUE TITLE
Scrap Addon (this addon) vs. Bagnon > Scrap Support

### ISSUE THREAD

**Issue by b-morgan** [Jaliborc/Scrap#227]
I have this addon installed (10.1.5) and I have [Bagnon](https://www.curseforge.com/wow/addons/bagnon) (10.1.11) installed. Do I also need [Bagnon > Scrap Support](https://www.curseforge.com/wow/addons/bagnon-scrap)?

**Comment by Jaliborc** [comment]
Yes
