### ISSUE TITLE
Left and right clicks cause fps drops

### ISSUE THREAD

**Issue by romper008** [Jaliborc/Scrap#236]
**Which software were you running?**
 - Addon version name: 10.1.8
 - Client used: Retail 10.2.0

**Please describe the bug.**
Everytime i do a left or right click, the screen freezes for a few milliseconds. Spamming one of those buttons will lead to a ~33% fps drop (e.g. 60->40 in Valdrakken)

**Please describe how to reproduce it.**
1. Just hold right mouse button and spam left mouse button

I found that this only happens when paired with another addon I use - PetTracker. Video proof: https://www.youtube.com/watch?v=QZIuMsDYUnQ

**Comment by Mike160770** [comment]
me2 - have to switch to "Selljunk" as long as this errors occur :-(
https://www.curseforge.com/wow/addons/sell-junk

**Comment by Kasamir** [comment]
Also happens to me. Only when paired with Pettracker
