### ISSUE TITLE
Errors using with Bagnon/Scrap

### ISSUE THREAD

**Issue by thelrohn** [Jaliborc/Scrap#24]
Using Scrap 13.8 with Bagnon 8.0.0 and Bagnon Scrap 19, and I'm getting these errors:

12x Error loading Scrap\Tests.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\TextButton.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\GrayButton.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\HelpButton.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\TabButtons.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\TextureButton.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\ColorPicker.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\IconCheck.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\TabGroup.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\Dropdown.lua
2x Error loading Scrap\Libs\Sushi-3.0\Classes\TextureDropdown.lua

The Bagnon Guild Bank and Void Storage modules are not active.

**Comment by KyrosKrane** [comment]
This error also happens without Bagnon. See #25 for more details on where these files are referenced.
