### ISSUE TITLE
Lua Error when opening SOD

### ISSUE THREAD

**Issue by TylerHancock96** [Jaliborc/Scrap#240]
**Which software were you running?**
 - Addon version name: Scrap
 - Client used: Classic 1.15.0.52409

**Have you read the changelog?**
Yes

**Please describe the bug.**
A Lua error appears when opening Classic Seasons of Discovery. I don't recall if this began happening before or after I installed the TitanBar Addon but it appears every time I join a server and/or reload the UI.

**Please describe how to reproduce it.**
1. Open WoW Classic
2. Join Server

**Any Screenshots?**
No Screenshot available

**Error Logs are Important!**
Date: 2023-12-06 21:10:17
ID: 1
Error occured in: Global
Count: 17
Message: Interface/AddOns/Scrap/addons/main/pricing.lua line 43:
   attempt to index local 'info' (a nil value)
Debug:
   [string "@Interface/AddOns/Scrap/addons/main/pricing.lua"]:43:
      Interface/AddOns/Scrap/addons/main/pricing.lua:40
   [string "=[C]"]: SetBagItem()
   [string "@Interface/AddOns/TitanClassicRepair/TitanClassicRepair.lua"]:611: TitanRepair_GetStatus()
   [string "@Interface/AddOns/TitanClassicRepair/TitanClassicRepair.lua"]:478: TitanRepair_GetInventoryInformation()
   [string "@Interface/AddOns/TitanClassicRepair/TitanClassicRepair.lua"]:369: TitanPanelRepairButton_OnUpdate()
   [string "@Interface/AddOns/TitanClassicRepair/TitanClassicRepair.lua"]:324: TitanPanelRepairButton_OnEvent()
   [string "*TitanClassicRepair.xml:14_OnEvent"]:1:
      [string "*TitanClassicRepair.xml:14_OnEvent"]:1
Locals:
tip = TitanRepairTooltip {
 0 = <userdata>
 layoutType = "TooltipDefaultLayout"
 GetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:294
 SetQuestLogItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:298
 comparing = false
 SetBorderBlendMode = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:306
 SetCraftItem = <function> defined =[C]:-1
 updateTooltip = 0.200000
 SetTradeSkillItem = <function> defined =[C]:-1
 __hasCounters = false
 __hasPrice = true
 TooltipBackdropOnLoad = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:275
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:302
 needsReset = true
 NineSlice = Frame {
 }
 SetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:290
 SetQuestItem = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
}
bag = 2
slot = 4
info = nil
(*temporary) = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:26
(*temporary) = <table> {
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 OnMail = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:68
 OnBag = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:40
 RegisterMessage = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 OnQuest = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:55
 AddLine = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:26
 OnSetCraftItem = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:83
 SendMessage = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:54
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 RegisterEvent = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterAllMessages = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 OnInventory = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:47
 OnLink = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:89
 OnSetTradeSkillItem = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:75
 OnEnable = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:13
 OnLoot = <function> defined @Interface/AddOns/Scrap/addons/main/pricing.lua:62
 UnregisterAllEvents = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 RegisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 NewModule = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 UnregisterEvent = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 Tag = "SCRAP_"
}
(*temporary) = TitanRepairTooltip {
 0 = <userdata>
 layoutType = "TooltipDefaultLayout"
 GetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:294
 SetQuestLogItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:298
 comparing = false
 SetBorderBlendMode = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:306
 SetCraftItem = <function> defined =[C]:-1
 updateTooltip = 0.200000
 SetTradeSkillItem = <function> defined =[C]:-1
 __hasCounters = false
 __hasPrice = true
 TooltipBackdropOnLoad = <function> defined @Interface/SharedXML/SharedTooltipTemplates.
AddOns:
  KalielsTracker, v1.5.0
  Swatter, v3.4.6977 (SwimmingSeadragon)
  AIVoiceOver, v1.4.2
  AIVoiceOverDataVanilla, v0.1
  AtlasLootClassic, vv3.2.0
  AtlasLootClassicData, vv3.2.0
  AtlasLootClassicDungeonsAndRaids, vv3.2.0
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Auctionator, v10.2.3
  BagBrother, v
  Bagnon, v10.2.4
  BagnonItemLevel, v2.0.85-Release
  Bartender4, v4.14.13
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  BetterAFK, v10.2.0.2_Classic_Dragonflight
  BetterVendorPrice, vv1.19.05
  BigWigs, vv305.2
  ClassicBestiary, v1.0.4
  ClassicCastbars, vv1.7.4
  DBMCore, v12497cb
  DBMStatusBarTimers, v12497cb
  Enchantrix, v3.4.6979 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  GreenWall, v1.11.11+classic-era
  GTFO, v5.5.3
  HandyNotes, vv1.6.17
  HighLevelAlert, v0.4.6
  Informant, v3.4.6980 (SwimmingSeadragon)
  LeatrixMaps, v1.15.06
  LeatrixPlus, v1.15.06
  LeatrixSounds, v1.15.06
  LFGBulletinBoard, v3.12
  MinimapButtonButton, v1.17.5
  MRT, v4810
  NovaInstanceTracker, v1.46
  NovaWorldBuffs, v2.59
  OmniCC, v10.2.1
  Prat30, v3.9.43
  Prat30Libraries, v
  ProjectAzilroka, v1.88
  Questie, v9.0.4
  RareScanner, v1.15.0.4
  RXPGuides, vv4.5.34
  Scrap, v10.2.2
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TitanClassic, v1.3.4.11404
  TitanClassicAmmo, v1.3.4.11404
  TitanClassicBag, v1.3.4.11404
  TitanClassicClock, v1.3.4.11404
  TitanClassicGold, v1.3.4.11404
  TitanClassicLocation, v1.3.4.11404
  TitanClassicLootType, v1.3.4.11404
  TitanClassicPerformance, v1.3.4.11404
  TitanClassicRegen, v1.3.4.11404
  TitanClassicRepair, v1.3.4.11404
  TitanClassicVolume, v1.3.4.11404
  TitanClassicXP, v1.3.4.11404
  TomTom, vv3.5.4-release
  totalRP3, v2.6.2
  totalRP3Data, v2.6.2
  TRP3LocationToggle, v1.12
  TwitchEmotes, vv2
  VuhDo, v3.156-vanilla
  VuhDoOptions, v3.156-vanilla
  WeakAuras, v5.8.7
  WhatsTraining, v5.0.2
  WIM, v3.10.16
  BlizRuntimeLib v1.15.0.52409(US) <enUS>
  (ck=911)

**Comment by b-morgan** [comment]
Same error here. Change line 43 in ...\Interface\AddOns\Scrap\addons\main\pricing.lua to:

`        if info then Prices:AddLine(tip, info.itemID, info.stackCount, true) end
`

**Comment by cdmichaelb** [comment]
Getting same error. I fixed it same way as @b-morgan but would like an official fix so I don't have to manually fix it every update ^_^
