### ISSUE TITLE
Lua Error When Opening Options Panel

### ISSUE THREAD

**Issue by TylerHancock96** [Jaliborc/Scrap#241]
**Which software were you running?**
 - Addon version name: Scrap (Junk Seller)
 - Client used: Classic/Seasons of Discovery v. 1.15.0.52409

**Have you read the changelog?**
 Yes

**Please describe the bug.**
When opening the options menu within the main menu, a lua error appears.

**Please describe how to reproduce it.**
1. Open Menu
2. Click on Options
3. See error

**Any Screenshots?**
N/A

**Error Logs are Important!**
Message: Interface/AddOns/Scrap/addons/config/tutorials.lua:46: attempt to index field 'Visualizer' (a nil value)
Time: Fri Dec  8 11:59:44 2023
Count: 1
Stack: Interface/AddOns/Scrap/addons/config/tutorials.lua:46: attempt to index field 'Visualizer' (a nil value)
[string "@Interface/AddOns/Scrap/addons/config/tutorials.lua"]:46: in function `?'
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...tie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Questie/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ce/AddOns/Questie/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/Scrap/addons/main/main.lua"]:43: in function <Interface/AddOns/Scrap/addons/main/main.lua:42>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2160: in function `SetUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:1966: in function `ShowUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:1873: in function <Interface_Vanilla/FrameXML/UIParent.lua:1869>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2652: in function `ShowUIPanel'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:369: in function `Open'
[string "*GameMenuFrame.xml:74_OnClick"]:2: in function <[string "*GameMenuFrame.xml:74_OnClick"]:1>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 ResetTutorials = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:207
 SendMessage = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:54
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 Restart = <function> defined @Interface/AddOns/Scrap/addons/config/tutorials.lua:65
 RegisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 TriggerTutorial = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:190
 NewModule = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 RegisterEvent = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 OnEnable = <function> defined @Interface/AddOns/Scrap/addons/config/tutorials.lua:9
 GetTutorials = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:222
 UnregisterAllEvents = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 Start = <function> defined @Interface/AddOns/Scrap/addons/config/tutorials.lua:61
 RegisterTutorials = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:179
 UnregisterEvent = <function> defined @Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 Tag = "SCRAP_"
}
(*temporary) = <function> defined @Interface/AddOns/Scrap/libs/Cus

**Comment by yourapple** [comment]
modify  Interface/AddOns/Scrap/addons/config/tutorials.lua:46 to this:
shine = Scrap.Visualizer and Scrap.Visualizer.ParentTab or nil,

**Comment by brittyazel** [comment]
I can confirm this issue happens upon each time opening the settings panel.

**Comment by johnatilley** [comment]
Similar issue with same first line message `attempt to index field 'Visualizer' (a nil value)`

For me it only appears on first UI load or after typing /reload, but doesn't appear when I go to the options. I never see the tutorial and it appears to be related to that. I can disable the options addon and run everything fine. It means I can't just change the options when I want to, I have to re-enable the addon and reload first and then disable it again after changing the options.

**Which software were you running?**
 - Addon version name: Scrap (Junk Seller)
 - Client used: Classic SoD: Version 1.15.0 (52409) (Release x64)

**Have you read the changelog?**
Yes

**Please describe the bug.**
When logging into the game or reloading the UI a lua error appears.
It appears when loading the add on it's own.
Disabling Scrap Options AddOn doesn't show the error so it's an issue with Scrap Options and not Scrap Merchant. I can useit without Scrap Options but obviously this means I cannot configure Scrap.
I never see the tutorial screen.
It breaks other plug ins such as GatherMate when they're all turned on.

**Please describe how to reproduce it.**
1. Log into WOW Classic.
2. See error.
3. Close error.
4. Type '/reload'
5. See error

**Error Logs are Important!**

**Error when loading just Scrap, Scrap Options and Scrap Merchant on their own**

Message: Interface/AddOns/Scrap/addons/config/tutorials.lua:46: attempt to index field 'Visualizer' (a nil value)
Time: Tue Dec 12 13:20:08 2023
Count: 1
Stack: Interface/AddOns/Scrap/addons/config/tutorials.lua:46: attempt to index field 'Visualizer' (a nil value)
[string "@Interface/AddOns/Scrap/addons/config/tutorials.lua"]:46: in function `?'
[string "@Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...ce/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ce/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Scrap/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...face/AddOns/Scrap/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/Scrap/addons/main/main.lua"]:40: in function `?'
[string "@Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...ce/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ce/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Scrap/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...face/AddOns/Scrap/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:391: in function `UIParentLoadAddOn'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:462: in function `TimeManager_LoadUI'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:720: in function <Interface_Vanilla/FrameXML/UIParent.lua:689>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 ResetTutorials = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:207
 SendMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 UnregisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 Restart = <function> defined @Interface/AddOns/Scrap/addons/config/tutorials.lua:65
 RegisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 TriggerTutorial = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:190
 NewModule = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 RegisterEvent = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 OnEnable = <function> defined @Interface/AddOns/Scrap/addons/config/tutorials.lua:9
 GetTutorials = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:222
 UnregisterAllEvents = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 Start = <function> defined @Interface/AddOns/Scrap/addons/config/

**Error with all my plugins (Not sure if relevant)**

Message: Interface/AddOns/Scrap/addons/config/tutorials.lua:46: attempt to index field 'Visualizer' (a nil value)
Time: Tue Dec 12 13:21:16 2023
Count: 1
Stack: Interface/AddOns/Scrap/addons/config/tutorials.lua:46: attempt to index field 'Visualizer' (a nil value)
[string "@Interface/AddOns/Scrap/addons/config/tutorials.lua"]:46: in function `?'
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/AI_VoiceOver/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...dOns/AI_VoiceOver/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/Scrap/addons/main/main.lua"]:40: in function `?'
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/AI_VoiceOver/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...dOns/AI_VoiceOver/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:391: in function `UIParentLoadAddOn'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:462: in function `TimeManager_LoadUI'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:720: in function <Interface_Vanilla/FrameXML/UIParent.lua:689>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 ResetTutorials = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:207
 SendMessage = <function> defined @Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 Restart = <function> defined @Interface/AddOns/Scrap/addons/config/tutorials.lua:65
 RegisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 TriggerTutorial = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:190
 NewModule = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 RegisterEvent = <function> defined @Interface/AddOns/AI_VoiceOver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 OnEnable = <function> defined @Interface/AddOns/Scrap/addons/config/tutorials.lua:9
 GetTutorials = <function> defined @Interface/AddOns/Scrap/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:222
 UnregisterAllEvents = <function> defined @Interface/AddOns/AI_Voice

**Comment by mehmetyildizdev** [comment]
> modify Interface/AddOns/Scrap/addons/config/tutorials.lua:46 to this: shine = Scrap.Visualizer and Scrap.Visualizer.ParentTab or nil,

this seems to get rid of the error message opening on options panel for me

**Comment by brittyazel** [comment]
I just put in a [pull request](https://github.com/Jaliborc/Scrap/pull/242) to fix this issue. The issue is that there are values within tutorials.lua in the "Config" internal-addon that need the "Merchant" internal-addon to already be loaded for them to be resolved. If you opened the settings panel prior to opening a merchant window, the "Merchant" internal-addon was not yet loaded, hence the error. My patch simply loads the "Merchant" internal-addon just before loading the "Config" internal-addon, thus making sure these values are resolved appropriately.

**Comment by gouletr** [comment]
as others have reported, also getting this when opening options:
```
Message: Interface/AddOns/Scrap/addons/config/tutorials.lua:46: attempt to index field 'Visualizer' (a nil value)
Time: Mon Dec 18 10:39:41 2023
Count: 1
Stack: Interface/AddOns/Scrap/addons/config/tutorials.lua:46: attempt to index field 'Visualizer' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Scrap/addons/config/tutorials.lua"]:46: in function `?'
[string "@Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...ce/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ce/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Attune/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ace/AddOns/Attune/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/Scrap/addons/main/main.lua"]:39: in function <Interface/AddOns/Scrap/addons/main/main.lua:39>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2160: in function `SetUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:1966: in function `ShowUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:1873: in function <Interface_Vanilla/FrameXML/UIParent.lua:1869>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2652: in function `ShowUIPanel'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:369: in function `Open'
[string "*GameMenuFrame.xml:74_OnClick"]:2: in function <[string "*GameMenuFrame.xml:74_OnClick"]:1>

Locals: (*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1
```

**Comment by Starlynk1** [comment]
Yup, very annoying error... not sure what the visualizer is, but its not happy it got moved in 10.2.1
