### ISSUE TITLE
Files missing from package

### ISSUE THREAD

**Issue by KyrosKrane** [Jaliborc/Scrap#25]
WoW is reporting that the following files are missing from Scrap. Either the references to them should be removed from the released package files, or the appropriate files and libraries should be included in the zip file users download.

This is with version 13.8, released today (2018-07-24).

In Scrap.toc:
Error loading Interface\AddOns\Scrap\Tests.lua

In Libs\Sushi-3.0\Sushi-3.0.xml
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\TextButton.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\GrayButton.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\HelpButton.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\TabButtons.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\TextureButton.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\ColorPicker.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\IconCheck.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\TabGroup.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\Dropdown.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\TextureDropdown.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\GlowBox.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\Editbox.lua
Error loading Interface\AddOns\Scrap\Libs\Sushi-3.0\Classes\Slider.lua

**Comment by Daeveren** [comment]
In Scrap.toc, add a # before Tests.lua (at the bottom). Addon author forgot to comment it out.

**Comment by thelrohn** [comment]
Commenting out Tests.lua does get rid of that error but the ones from Sushi-3.0 persist. Unfortunately I can't tell from BugSack what's trying to load those.

**Comment by KyrosKrane** [comment]
I posted that in my first post:

Scrap\Libs\Sushi-3.0\Sushi-3.0.xml

Just delete the lines that mention the files I listed, or you can comment them out with
