### ISSUE TITLE
no longer works with TSM4

### ISSUE THREAD

**Issue by Daeveren** [Jaliborc/Scrap#27]
The addon no longer works when using TradeSkillMaster 4.

**Comment by KyrosKrane** [comment]
I use TSM4 and it seems to be working fine. What specifically is going wrong?

**Comment by Daeveren** [comment]
Guess the issue can be closed, I no longer have any issues with it. Most likely it was an issue from TSM that they since resolved (they had a ton of issues with other addons due to interfering with the Vendor UI).
