### ISSUE TITLE
Junk/Useful tabs not working

### ISSUE THREAD

**Issue by aleczero** [Jaliborc/Scrap#35]
The Junk and Useful tabs when interacting with a vendor are now showing any items. Due to this, Scrap keeps vendoring my goblin gliders.
<img width="1024" alt="untitled" src="https://user-images.githubusercontent.com/9851458/45576773-77ef2300-b82d-11e8-9eaa-c57bfad09535.png">

**Comment by chazwhiz** [comment]
Same issue, the tabs don't seem to be functioning at all.

**Comment by Faithfinder** [comment]
+1, tries to sell my drums to vendor. Uhh

**Comment by omegavladd** [comment]
Please right click on the Sell Junk button and select tutorial for proper usage of this feature :)
