### ISSUE TITLE
Scrap button showing when visualizer is disabled

### ISSUE THREAD

**Issue by Pegoth** [Jaliborc/Scrap#37]
The Scrap_Merchant part checks if visualizer is enabled, but the API changed in 6.0.2.

Need to change Scrap_Merchant.lua, line 81 from
```lua
if select(5, GetAddOnInfo('Scrap_Visualizer')) then
```
to
```lua
local loadable, reason = select(4, GetAddOnInfo('Scrap_Visualizer'))
if loadable or reason == nil or reason == "DEMAND_LOADED" then
```

(p.s.: Not sure about _loadable_, it's SUPPOSED to be true when loaded or loadable according to wiki, but seems to be always false for Scrap_Visualizer)

**Comment by Jaliborc** [comment]
Nice catch, did not notice that change
