### ISSUE TITLE
IsBetterEquip not working correctly

### ISSUE THREAD

**Issue by norecha** [Jaliborc/Scrap#48]
IsBetterEquip is calling GetInventoryItemID with slot variable as string, where it should be an int. this results in always head slot being returned.

It also does not get proper item level if item is timewarped. I noticed this because it wasn't showing a junk glove as junk, because it was comparing every single item to head slot, and my head slot was a 365 timewarped item, but it was using original item level.

**Comment by Jaliborc** [comment]
I'll look into it. Thank you for the feedback

**Comment by Jaliborc** [comment]
Done, nice catch
