### ISSUE TITLE
Please add default exclusion for Gnomish Army Knife and its Ultmate versions.

### ISSUE THREAD

**Issue by Xastabus** [Jaliborc/Scrap#50]
I love Scrap.  However, I have the multi-profession multi-tool Gnomish Army Knife (ID: 40772) or Ultimate Gnomish Army Knife (ID:114943 & 109253) on multiple characters.  I have to manually add these items to Scrap's "useful" on every new character and sometimes it gets sold before I remember.  It would be nice to have these items added to a global exclusion list so they never get sold by accident.

Thanks!

**Comment by Jaliborc** [comment]
Added in internal build
