### ISSUE TITLE
Blackweald Chestguard

### ISSUE THREAD

**Issue by OddMoon** [Jaliborc/Scrap#55]
Hello there. On two occasions, Scrap decided to destroy Blackweald Chestguard when I visited a vendor. First time I didnt notice it, believing I miscounted the pieces of Azerite armor pieces I had in my inventory, so I thought little of it. Second time however, it was a 400 ilvl piece and I saw it just vanish from my inventory when I visited a vendor. I restored it via Blizzards services, but accidentally got it deleted again when I visited a vendor again. I would like this to be fixed as I very much like this addon and having to disable it in case it does this with other valuable items is something im not a fan of. Please fix this when you have time. Good day :)

**Comment by Jaliborc** [comment]
Can't find item
