### ISSUE TITLE
No Gold Coin Icon in Adibags

### ISSUE THREAD

**Issue by Rave96** [Jaliborc/Scrap#56]
**Running Software (please complete the following information):**
 - Game build: newest
 - Addon version: newest

**Describe the bug**
I'm using Adibags and really love the hotkey for marking items as junk, but the gold coin doesnt appear on the items in the inventory. With the default blizzard bags everything works and the gold coin appears on the items. (so this probably is a compatibility problem with adibags and scrap, but i dont know on which part ^^')
Adibags also has a function to put the junk items into a category (which only works after a /reload and is an Adibags problem) 

**To Reproduce**
1. Having scrap and adibags installed
2. marking an item as junk
3. no gold coin appearing on the item

**Expected behavior**
A gold coin appearing on the top right of the item

**Comment by Jaliborc** [comment]
Scrap only marks the default bags. Some other addons have plugins that show Scrap, but unless someone develops one for Adibags it won't.

I cannot help you.
