### ISSUE TITLE
lua error message - seems to be a random issue

### ISSUE THREAD

**Issue by OldSubSailor** [Jaliborc/Scrap#60]
VERSION 8.2.0 
got this when clicking on a merchant. (WoW Classic)
Date: 2019-09-05 05:27:06
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Scrap_Merchant\Scrap_Merchant.lua line 290:
   attempt to call global 'GetGuildBankWithdrawMoney' (a nil value)
Debug:
   Scrap_Merchant\Scrap_Merchant.lua:290: Repair()
   Scrap_Merchant\Scrap_Merchant.lua:110: OnMerchant()
   Scrap_Merchant\Scrap_Merchant.lua:98: ?()
   Scrap\Scrap.lua:77:
      Scrap\Scrap.lua:77
Locals:
self = Scrap {
 0 = <userdata>
 OnLeave = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:167
 PrintMoney = <function> defined @Interface\AddOns\Scrap\Scrap.lua:301
 CheckFilters = <function> defined @Interface\AddOns\Scrap\Scrap.lua:162
 VARIABLES_LOADED = <function> defined @Interface\AddOns\Scrap\Scrap.lua:84
 ShowTooltip = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:141
 LowLevel = <function> defined @Interface\AddOns\Scrap\Scrap.lua:194
 Junk = <table> {
 }
 IsBetterEquip = <function> defined @Interface\AddOns\Scrap\Scrap.lua:226
 GetSlot = <function> defined @Interface\AddOns\Scrap\Scrap.lua:240
 OnMerchant = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:104
 OnItemSold = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:307
 LoadTooltip = <function> defined @Interface\AddOns\Scrap\Scrap.lua:254
 Repair = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:287
 AnyJunk = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:280
 tab = MerchantFrameSecureTab0 {
 }
 ToggleJunk = <function> defined =[C]:-1
 Print = <function> defined @Interface\AddOns\Scrap\Scrap.lua:305
 GetBuypackStack = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:356
 OnItemRefund = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:332
 IterateJunk = <function> defined @Interface\AddOns\Scrap\Scrap.lua:118
 GetJunkValue = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:265
 IsLowEquip = <function> defined @Interface\AddOns\Scrap\Scrap.lua:206
 SellJunk = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:222
 UpdateButtonPosition = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:201
 BelongsToSet = <function> defined @Interface\AddOns\Scrap\Scrap.lua:271
 CanGuildRepair = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:300
 OnEnter = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:135
 IsJunk = <function> defined @Interface\AddOns\Scrap\Scrap.lua:112
 HighLevel = <function> defined @Interface\AddOns\Scrap\Scrap.lua:190
 OnReceiveDrag = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:188
 HasSpotlight = true
 GetID = <function> defined @Interface\AddOns\Scrap\Scrap.lua:315
 ToggleCursorJunk = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:253
 IsSoulbound = <function> defined @Interface\AddOns\Scrap\Scrap.lua:275
 OnClick = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:174
 UpdateButtonState = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:195
 BAG_UPDATE = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:128
 MERCHANT_CLOSED = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:123
 MERCHANT_SHOW = <function> defined @Interface\AddOns\Scrap_Merchant\Scrap_Merchant.lua:95
 CombatItem = <function> defined @Interface\AddOns\Scrap\Scrap.lua:202
 IsOtherClass = <function> defined @Interface\AddOns\Scrap\Scrap.lua:289
 StandardQuality = <function> defined @Interface\AddOns\Scrap\Scrap.lua:198
}
cost = 4
(*temporary) = nil
(*temporary) = "attempt to call global 'GetGuildBankWithdrawMoney' (a nil value)"
L = <table> {
 Removed = "Set as useful: %s"
 SoldJunk = "You sold your junk for %s"
 Tutorial_Button = "Scrap will automatically sell all your junk whenever you visit a merchant. But you can manually sell it: simply Left-Click on the Scrap button.

Right-Click on the button to bring extra options."
 Added = "Set as junk: %s"
 SafeMode = "Safe Mode"
 ShowTutorials = "Show Tutorials"
 LowConsume = "Low Consumables"
 Junk = "Junk"
 Tutorial_Drag = "What if you want to tell Scrap which items to sell or not? Simply Drag it from your bags into the Scrap button.

Alternatively, you may set a Keybinding at the Game Menu options. Press it while hovering the item."
 Learn = "Intel
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Ace3, v
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  Informant, v8.2.6374 (SwimmingSeadragon)
  Questie, v4.0.15 BETA
  Scrap, v13.18
  ScrapMerchant, v13.18
  ScrapSpotlight, v13.18
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=30a)

**Comment by Jaliborc** [comment]
Fixed in 13.19

**Comment by OldSubSailor** [comment]
Thank you
