### ISSUE TITLE
Coin icon 23-12-2019

### ISSUE THREAD

**Issue by Twentyeight2570** [Jaliborc/Scrap#65]
I cant see the c
![Coin icon](https://user-images.githubusercontent.com/59181474/71380461-8e0e9600-25cf-11ea-8532-533f2a3b269b.png)
oin icon. I should be able to see it but i dont know if something is blocking it. because when i go to settings its grey.

**Comment by ImRobGit86** [comment]
Same here, coin icon is no longer visible. I'm using Bagnon addon, it was recently updated 2 days ago. Not sure if the issue is with Scrap or Bagnon.

**Comment by OrionR0** [comment]
Is this possibly related to the following error that I just got after updating Bagnon? I suspect the keyring support that's new to Bagnon may be causing this issue.

------------------------------
Date: 2019-12-24 00:29:56
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua line 20:
   attempt to index local 'ItemSlot' (a nil value)
Debug:
   Bagnon_Scrap\Bagnon_Scrap.lua:20: in main chunk
Locals:
Addon = <table> {
 IsKeyring = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:375
 IsRetail = false
 GetOwnerID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:270
 Frames = <table> {
 }
 InBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:352
 ItemGroup = <table> {
 }
 RestoreItemData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:304
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:379
 RegisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsBagCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:291
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:275
 Slash = "bgn"
 OnEnable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:98
 Name = "Bagnon"
 IterateOwners = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:114
 InGuild = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:360
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 RestoreLinkData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:328
 Item = <table> {
 }
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 SortButton = <table> {
 }
 InventoryFrame = <table> {
 }
 Title = <table> {
 }
 BagGroup = <table> {
 }
 SearchToggle = <table> {
 }
 Events = <table> {
 }
 SearchFrame = <table> {
 }
 TooltipCounts = <table> {
 }
 BrokerDisplay = <table> {
 }
 LDB = <table> {
 }
 Tag = "BAGNON_"
 PickupItem = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:250
 IsBackpackBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:371
 IsOwnerCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:287
 AutoDisplay = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Sorting = <table> {
 }
 BankFrame = <table> {
 }
 Parented = <table> {
 }
 GetItemID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:229
 IsReagents = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:387
 IsBankBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:383
 Owners = <table> {
 }
 ShowOptions = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:157
 GetBagInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
 DropButton = <table> {
 }
 BagToggle = <table> {
 }
 Rules = <table> {
 }
 GetOwnerInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:74
 MoneyFrame = <table> {
 }
 Tipped = <table> {
 }
 RegisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Interface\AddOns\Atl
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.25
  BagnonScrap, v8.2.0
  Scrap, v13.19
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=331)
