### ISSUE TITLE
Scrap Not Working Just Throws Lua Error

### ISSUE THREAD

**Issue by Chzconey** [Jaliborc/Scrap#67]
Date: 2019-12-26 01:18:03
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Scrap\addons\main\main.lua line 95:
   attempt to index field 'ml' (a nil value)
Debug:
   (tail call): ?
   Scrap\addons\main\main.lua:95: IsJunk()
   Scrap\addons\main\main.lua:127: (for generator)()
   Scrap\addons\merchant\button.lua:215: GetReport()
   Scrap\addons\merchant\button.lua:187: Sell()
   Scrap\addons\merchant\button.lua:62: OnMerchant()
   Scrap\addons\merchant\button.lua:45: ?()
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [C]: ?
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: LoadAddOn()
   Scrap\addons\main\main.lua:52:
      Scrap\addons\main\main.lua:52
   [C]: ?
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AtlasQuest, v4.11.58
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AutoLootPlus, v2.0.0-11302
  BadBoy, vv1-classic
  BagBrother, v
  Bagnon, v8.2.26
  BankStack, vv11302.0
  Bartender4, v4.8.9
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.11.00
  BootyBayGazette, v6.1.20191223
  ClassicSpellActivations, v
  D4KiRMissingPower, v3.1 Release
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1303r001
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Diminish, vv2.2.5
  DiminishOptions, v
  EasyMail, v4.3
  FastGuildInvite, v59
  GatherMate2, v1.45.5
  GTFO, v4.51
  Guidelime, v1.040
  GuidelimeSage, v1.0
  HealBot, v1.13.3.1
  HealBotData, v1.13.3.0
  HealBoten, v1.13.3.0
  HealBotOptions, v1.13.3.0
  HealBotTips, v1.13.3.1
  honorspy, v1.6.7
  InFlightLoad, v1.13.003
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  KillTrack, vv1.13.0
  LeatrixMaps, v1.13.41
  LeatrixPlus, v1.13.42
  LetMeCast, v1.3
  LibSharedMedia30, v3.0-113
  lsToasts, v11302.02
  Mapster, v1.8.5
  Masque, v8.2.8-Classic
  MasqueRaeli, vr19-release
  MBB, v4.0
  MikScrollingBattleText, v5.7.149
  MissingTradeSkillsList, v1.13.28
  Misspelled, v1.7.4
  MonkeyClock, vv3.2.0
  MonkeySpeed, vv3.4.0
  NeatPlates, v1.13.3.2
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniBar, vv10.7
  OmniCC, v8.3.1
  Peggle, v2.2.6
  Prat30, v3.7.45
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  QuartzProcs, v3.6
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.4.1
  RealMobHealth, v2.17
  Scrap, v8.2.0
  ScrapMerchant, v
  ShadowedUnitFrames, vv4.2.2-Classic
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SimpleMap, v1.2.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SmartQuest, v1.18
  Spy, v1.0.20
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TalentSequence, v2.0
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TitanSocial, v1.13.3
  TomTom, vv11303-1.0.9
  TotalQuestXP, v1.7
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  TrinketMenu, v7.3.2
  TwitchEmotes, vv2
  VendorPrice, v1.3.0
  WeakAuras, v2.15.5
  WeakAurasCompanion, v1.0.0
  WeaponSwingTimer, v4.1.0
  WhatsTraining, v1.8.7
  WIM, v3.8.4
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=e50)

**Comment by XinYenFon** [comment]
```Message: Interface\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua:20: attempt to index local 'ItemSlot' (a nil value)
Time: Thu Dec 26 10:42:13 2019
Count: 1
Stack: Interface\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua:20: attempt to index local 'ItemSlot' (a nil value)
Interface\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua:20: in main chunk

Locals: Addon = <table> {
 IsKeyring = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:375
 IsRetail = true
 GetOwnerID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:270
 Frames = <table> {
 }
 InBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:352
 ItemGroup = <table> {
 }
 RestoreItemData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:304
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:379
 RegisterMessage = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsBagCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:291
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:275
 Slash = "bgn"
 OnEnable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:98
 Name = "Bagnon"
 IterateOwners = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:114
 InGuild = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:360
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 RestoreLinkData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:328
 Item = <table> {
 }
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 SortButton = <table> {
 }
 InventoryFrame = <table> {
 }
 Title = <table> {
 }
 BagGroup = <table> {
 }
 SearchToggle = <table> {
 }
 Events = <table> {
 }
 SearchFrame = <table> {
 }
 TooltipCounts = <table> {
 }
 BrokerDisplay = <table> {
 }
 LDB = <table> {
 }
 Tag = "BAGNON_"
 PickupItem = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:250
 IsBackpackBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:371
 IsOwnerCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:287
 AutoDisplay = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Sorting = <table> {
 }
 BankFrame = <table> {
 }
 Parented = <table> {
 }
 GetItemID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:229
 IsReagents = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:387
 IsBankBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:383
 Owners = <table> {
 }
 ShowOptions = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:157
 GetBagInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\lib```

**Comment by rainfordays** [comment]
I also have numerous lua errors with this since the latest update and they are all referencing trying to index field "ml" which is nil. Forgot to initialize this value?

**Comment by XinYenFon** [comment]
There is a small typo actually... 

In Scrap\addons\main\main.lua
```
return self.junk[id] or (self.sets.learn and self.sets.ml[id] and self.sets.ml[id] >= 1) or self:IsFiltered(id, ...)
```

While it needs to be
```
return self.junk[id] or (self.sets.learn and self.charsets.ml[id] and self.charsets.ml[id] >= 1) or self:IsFiltered(id, ...)
```

**Comment by XinYenFon** [comment]
I have to post another update, while everything so far seems good, if you enable AI learning in Scrap addon its creating another lua error related to `CheckFilters` which does not exist in the files. I assume this is a left-over from old code (which btw the fuction exist in old version). As again I am not sure if its intended that way or function didn't ported to new version but I give my FYI to you guys.

**Comment by Jaliborc** [comment]
Quick catch guys. I'll go test it and upload a new version.
