### ISSUE TITLE
Bagnon was rewritten

### ISSUE THREAD

**Issue by Kanegasi** [Jaliborc/Scrap#7]
A new Bagnon beta version was released, Bagnon Scrap no longer highlights junk.

**Comment by Jaliborc** [comment]
Thank you for the warning! But I'm Bagnon's developer too :D Will release new version when the Bagnon beta build becomes stable for release.

**Comment by Kanegasi** [comment]
Oh good lord, I didn't catch that. Thank you for the reply anyways lmao.

While I'm here, I have two other things. I'll make separate issues for them if you want.

1. Beta BagBrother's tooltip counts aren't showing. I have TipTac installed if that means anything, but current release tooltips work with TipTac.

2. Would you mind tossing in an item level filter to Scrap? I replace your IsJunk function to add it myself. I do this because I want the AI to record the trash gear from world quests, but I don't want to toss a lucky WF/TF if I get one.
