### ISSUE TITLE
Lua Error On Selling Items

### ISSUE THREAD

**Issue by Chzconey** [Jaliborc/Scrap#70]
**Running Software (issues missing this information will be deleted):**
 - Addon version:8.21
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. READ

**Describe the bug**
Lua Error on sale of items
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Vendor
2. Click on item to sell
3. See error

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.
Date: 2019-12-26 14:57:10
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Scrap\addons\merchant\learning.lua line 41:
   attempt to call method 'CheckFilters' (a nil value)
Debug:
   [C]: CheckFilters()
   Scrap\addons\merchant\learning.lua:41: OnItemSold()
   Scrap\addons\merchant\learning.lua:26:
      Scrap\addons\merchant\learning.lua:24
   [C]: UseContainerItem()
   ..\FrameXML\ContainerFrame.lua:1254: ContainerFrameItemButton_OnClick()
   [string "*:OnClick"]:12:
      [string "*:OnClick"]:1
   [C]: ?
Locals:

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AtlasQuest, v4.11.58
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AutoLootPlus, v2.0.0-11302
  BadBoy, vv1-classic
  BagBrother, v
  Bagnon, v8.2.27
  BagnonScrap, v8.2.1
  BankStack, vv11302.0
  Bartender4, v4.8.9
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.11.00
  BootyBayGazette, v6.1.20191223
  ClassicSpellActivations, v
  D4KiRMissingPower, v3.1 Release
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1303r001
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Diminish, vv2.2.5
  DiminishOptions, v
  EasyMail, v4.3
  FastGuildInvite, v59
  GatherMate2, v1.45.5
  GTFO, v4.51
  Guidelime, v1.040
  GuidelimeSage, v1.0
  HealBot, v1.13.3.1
  HealBotData, v1.13.3.0
  HealBoten, v1.13.3.0
  HealBotOptions, v1.13.3.0
  HealBotTips, v1.13.3.1
  honorspy, v1.6.7
  InFlightLoad, v1.13.003
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  KillTrack, vv1.13.0
  LeatrixMaps, v1.13.41
  LeatrixPlus, v1.13.42
  LetMeCast, v1.3
  LibSharedMedia30, v3.0-113
  lsToasts, v11302.02
  Mapster, v1.8.5
  Masque, v8.2.8-Classic
  MasqueRaeli, vr19-release
  MBB, v4.0
  MikScrollingBattleText, v5.7.149
  MissingTradeSkillsList, v1.13.28
  Misspelled, v1.7.4
  MonkeyClock, vv3.2.0
  MonkeySpeed, vv3.4.0
  NeatPlates, v1.13.3.2
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniBar, vv10.7
  OmniCC, v8.3.1
  Peggle, v2.2.6
  Prat30, v3.7.45
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  QuartzProcs, v3.6
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.4.1
  RealMobHealth, v2.17
  Scrap, v8.2.1
  ScrapBroker, v8.2.1
  ScrapMerchant, v
  ShadowedUnitFrames, vv4.2.2-Classic
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SimpleMap, v1.2.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SmartQuest, v1.18
  Spy, v1.0.20
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TalentSequence, v2.0
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TitanSocial, v1.13.3
  TomTom, vv11303-1.0.9
  TotalQuestXP, v1.7
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  TrinketMenu, v7.3.2
  TwitchEmotes, vv2
  VendorPrice, v1.3.0
  WeakAuras, v2.15.5
  WeakAurasCompanion, v1.0.0
  WeaponSwingTimer, v4.1.0
  WhatsTraining, v1.8.7
  WIM, v3.8.4
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=e7c)

**Additional context**

**Comment by Jaliborc** [comment]
Yup, yup. Fixed and releasing new version
