### ISSUE TITLE
Sell junk key doesn't work starting from version 8.2.0

### ISSUE THREAD

**Issue by iJSmile** [Jaliborc/Scrap#72]
**Running Software (issues missing this information will be deleted):**
 - Addon version: starting from 8.2.0

 **Have you read the changelog? (please don't waste our time)**
I think yes

**Describe the bug**
Selling the junk using keyboard key doesn't work 

**Steps:**
1. Install addon version 8.2.0 or higher
2. Disable all other addons
3. ESC -> Key Bindings -> AddOns -> Sell junk -> assign any key
4. Open vendor and sell junk using assigned key from step 3

**Screenshots**
Versions in red - key doesn't work.
Version in green - key works fine.
![image](https://user-images.githubusercontent.com/2786485/71580880-a7ee3280-2b13-11ea-9ed4-482f4814c14e.png)

**Comment by Jaliborc** [comment]
Fixed internally
