### ISSUE TITLE
Character Specific Junk list option reset on logout / reload - Global Junk list not possible.

### ISSUE THREAD

**Issue by davans** [Jaliborc/Scrap#75]
**Running Software 
 - Addon version:  Scrap-8.2.2-8.2.5.zip  (Twitch Client)
 - Server patch: 8.2.5 (32750)

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.  Yes change log has been reviewed.

**Describe the bug**
Character Specific Junk list option resets after login / client reset so it is not possible to have a global junk list for all characters.

**To Reproduce**
Steps to reproduce the behaviour,  with only the Scrap addon and config loaded
1. Go to 'Game Menu'
2. Click on 'Interface,  AddOns.'
3. Scroll down to 'Scrap'
4. De-Select the option next to "Character Specific Junk list" to enable global junk list (non character specific)
5. Logout or /reset
6 check the option and it is back enabled limiting to list for this character.
Image taken,  on login.
![image](https://user-images.githubusercontent.com/3532801/71926176-a2838e80-318a-11ea-97be-b4172d20ee7e.png)
Image Taken when option is changed
![image](https://user-images.githubusercontent.com/3532801/71926971-56d1e480-318c-11ea-96cc-7cf5594fc3f5.png)

No error is shown using the "/console scriptErrors 1", 

**Expected behaviour**
Option should not reset to enabled,  you should be able to setup a global junk list as used in previous versions of the addon.

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by Jaliborc** [comment]
Fixed internally
