### ISSUE TITLE
How to fix these errors 

### ISSUE THREAD

**Issue by Whisperken** [Jaliborc/Scrap#76]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3
 - Server patch: [e.g. Build 8.3.0.33084]

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**When i start the game i get this error:**

Date: 2020-01-18 14:20:37
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\Scrap\addons\main\main.lua line 66:
   bad argument #1 to 'setmetatable' (table expected, got nil)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: setmetatable()
   [string "@Scrap\addons\main\main.lua"]:66: OnSettings()
   [string "@Scrap\addons\main\main.lua"]:54: ?()
   [string "@Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua"]:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   [string "@Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua"]:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [string "=[C]"]: ?
   [string "@SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua"]:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   [string "@SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [string "=[C]"]: LoadAddOn()
   [string "@..\FrameXML\UIParent.lua"]:457: UIParentLoadAddOn()
   [string "@..\FrameXML\UIParent.lua"]:580: TimeManager_LoadUI()
   [string "@..\FrameXML\UIParent.lua"]:1257:
      ..\FrameXML\UIParent.lua:1155
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AutoLootPlus, v2.0.0-80200
  AzeritePowerWeights, v8.3.1
  BagBrother, v
  Bagnon, v8.3.1
  Bartender4, v4.8.9
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  DBMCore, v8.3.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GarrisonCommanderBroker, v3.2.4 1.1.0
  GatherMate2, v1.45.5
  Grail, v106
  GrailNPCsretail, v27178
  GrailNPCsretailenUS, v27178
  GrailQuestsretail, v31478
  GrailQuestsretailenUS, v31478
  GrailReputationsretail, v007
  HandyNotes, vv1.5.9
  Oilvl, v8.2.1
  Pawn, v2.3.17
  Prat30, v3.7.45
  Prat30Libraries, v
  RaiderIO, v8.1.0 (v202001170600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  Recount, vv8.3.0a
  Scrap, v8.3.0
  ShadowedUnitFrames, vv4.2.8
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.5.80300
  TitanBag, v5.18.5.80300
  TitanClock, v5.18.5.80300
  TitanGold, v5.18.5.80300
  TitanLocation, v5.18.5.80300
  TitanLootType, v5.18.5.80300
  TitanPerformance, v5.18.5.80300
  TitanRepair, v5.18.5.80300
  TitanVolume, v5.18.5.80300
  TitanXP, v5.18.5.80300
  TomTom, vv80300-1.1.0
  TradeSkillMaster, vv4.9.16
  TradeSkillMasterAppHelper, vv4.0.7
  Wholly, v076
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=6e6)

**After that i go to a vendor and i click scrap i get this error:**

Date: 2020-01-18 14:24:36
ID: 4
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\Scrap\addons\merchant\visualizer.lua line 98:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: pairs()
   [string "@Scrap\addons\merchant\visualizer.lua"]:98: QueryList()
   [string "@Scrap\addons\merchant\visualizer.lua"]:84:
      ...nterface\AddOns\Scrap\addons\merchant\visualizer.lua:83
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AutoLootPlus, v2.0.0-80200
  AzeritePowerWeights, v8.3.1
  BagBrother, v
  Bagnon, v8.3.1
  BagnonConfig, v
  Bartender4, v4.8.9
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  DBMCore, v8.3.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GarrisonCommanderBroker, v3.2.4 1.1.0
  GatherMate2, v1.45.5
  Grail, v106
  GrailAchievements, v011
  GrailNPCsretail, v27178
  GrailNPCsretailenUS, v27178
  GrailQuestsretail, v31478
  GrailQuestsretailenUS, v31478
  GrailReputationsretail, v007
  HandyNotes, vv1.5.9
  Informant, v8.2.6508 (SwimmingSeadragon)
  Oilvl, v8.2.1
  Pawn, v2.3.17
  Prat30, v3.7.45
  Prat30Libraries, v
  RaiderIO, v8.1.0 (v202001170600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  Recount, vv8.3.0a
  Scrap, v8.3.0
  ScrapMerchant, v
  ShadowedUnitFrames, vv4.2.8
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.5.80300
  TitanBag, v5.18.5.80300
  TitanClock, v5.18.5.80300
  TitanGold, v5.18.5.80300
  TitanLocation, v5.18.5.80300
  TitanLootType, v5.18.5.80300
  TitanPerformance, v5.18.5.80300
  TitanRepair, v5.18.5.80300
  TitanVolume, v5.18.5.80300
  TitanXP, v5.18.5.80300
  TomTom, vv80300-1.1.0
  TradeSkillMaster, vv4.9.16
  TradeSkillMasterAppHelper, vv4.0.7
  Wholly, v076
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=750)

**Comment by Andrew1175** [comment]
I'm receiving this error as well. Addon is no longer working as of 1/17/2020

**Comment by Cakedonut** [comment]
I'm getting this error too. I managed to fix the error I think, or at least it is working for me. Go into your addon folder and find main.lua for Scrap. It should be located at _retail_\Interface\AddOns\Scrap\addons\main\main.lua. Find line 63 in that file, which should look like the following:

`Scrap_CharSets = Scrap_CharSets or {list = {}, ml = {}}`

Change it to this:

`Scrap_CharSets = Scrap_CharSets or {list = {}, ml = {}, share = {}}`

Then /reload or restart game and the addon should function correctly.

**Comment by Whisperken** [comment]
> I'm getting this error too. I managed to fix the error I think, or at least it is working for me. Go into your addon folder and find main.lua for Scrap. It should be located at _retail_\Interface\AddOns\Scrap\addons\main\main.lua. Find line 63 in that file, which should look like the following:
> 
> `Scrap_CharSets = Scrap_CharSets or {list = {}, ml = {}}`
> 
> Change it to this:
> 
> `Scrap_CharSets = Scrap_CharSets or {list = {}, ml = {}, share = {}}`
> 
> Then /reload or restart game and the addon should function correctly.

Hey @Cakedonut I just tried doing that and I'm still receiving the same error :/

**Comment by Cakedonut** [comment]
> 
> 
> > I'm getting this error too. I managed to fix the error I think, or at least it is working for me. Go into your addon folder and find main.lua for Scrap. It should be located at _retail_\Interface\AddOns\Scrap\addons\main\main.lua. Find line 63 in that file, which should look like the following:
> > `Scrap_CharSets = Scrap_CharSets or {list = {}, ml = {}}`
> > Change it to this:
> > `Scrap_CharSets = Scrap_CharSets or {list = {}, ml = {}, share = {}}`
> > Then /reload or restart game and the addon should function correctly.
> 
> Hey @Cakedonut I just tried doing that and I'm still receiving the same error :/

@Whisperken, do you use Twitch to manage your addons or some other addon manager? Try deleting all your saved settings for the addon, which is really easy to do if you use Twitch (simply right-click the addon in your installed addons list and click "Delete Settings (Saved Variables)". If that doesn't work, try completely deleting the addon and any of the associated saved settings (which can be found in the _retail_/WTF folder). Then, re-install the addon, patch that line, and try again. And if that doesn't work, sorry, I don't know. :( Hopefully the addon author can chime in or try to help track down this issue.

**Comment by Whisperken** [comment]
@Cakedonut That worked I deleted the settings after that the mod from twitch after that i deleted the files you mentioned and now it works, thanks alot!!

**Comment by Jaliborc** [comment]
As stated in the issue submission template, please make sure to provide the error with ID: 1.
Can't fix anything if I only get an error with a higher ID.
