### ISSUE TITLE
Set as useful button don't work

### ISSUE THREAD

**Issue by zalewskigrzegorz** [Jaliborc/Scrap#79]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.0
 - Server patch: Build 8.3.0.33169

**Describe the bug**
Set as useful button don't work and generate an error

**To Reproduce**
1. Go to vendor window
2. Click on Scrap tab
3. Select item
4. Click on Set as useful button 

**Expected behavior**
Set as a useful button should move the item to useful

**Error Logs**
`3x [string "ScrapVisualizerButton:OnClick"]:1: attempt to call method 'ToggleCurrent' (a nil value)
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = ScrapVisualizerButton {
 0 = <userdata>
 Text = ScrapVisualizerButtonText {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 Left = <unnamed> {
 }
}
button = "LeftButton"
down = false
(*temporary) = nil
(*temporary) = ScrapVisualizer {
 SendSignal = <function> defined @Scrap\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 TitleText = ScrapVisualizerTitleText {
 }
 portrait = ScrapVisualizerPortrait {
 }
 NewModule = <function> defined @Scrap\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 SetPortraitShown = <function> defined @SharedXML\PortraitFrame.lua:52
 ToggleItem = <function> defined @Scrap\addons\merchant\visualizer.lua:75
 Inset = ScrapVisualizerInset {
 }
 SetPortraitTextureRaw = <function> defined @SharedXML\PortraitFrame.lua:40
 OnShow = <function> defined @Scrap\addons\merchant\visualizer.lua:52
 selectedTab = 1
 TitleBg = <unnamed> {
 }
 numTabs = 2
 UpdateList = <function> defined @Scrap\addons\merchant\visualizer.lua:108
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML\PortraitFrame.lua:68
 Tab2 = ScrapVisualizerTab2 {
 }
 list = <table> {
 }
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 PixelSnapDisabled = true
 UpdateButton = <function> defined @Scrap\addons\merchant\visualizer.lua:185
 SetTitle = <function> defined @SharedXML\PortraitFrame.lua:60
 Tag = "SCRAP_"
 tab = MerchantFrameSecureTab0 {
 }
 Spinner = <unnamed> {
 }
 SetItem = <function> defined @Scrap\addons\merchant\visualizer.lua:69
 Scroll = ScrapVisualizerScroll {
 }
 SetBorder = <function> defined @SharedXML\PortraitFrame.lua:27
 layoutType = "PortraitFrameTemplate"
 SetTab = <function> defined @Scrap\addons\merchant\visualizer.lua:64
 OnHide = <function> defined @Scrap\addons\merchant\visualizer.lua:57
 OnEnable = <function> defined @Scrap\addons\merchant\visualizer.lua:24
 item = <table> {
 }
 SetPortraitAtlasRaw = <function> defined @SharedXML\PortraitFrame.lua:44
 Button = ScrapVisualizerButton {
 }
 SendMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 Bg = ScrapVisualizerBg {
 }
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UnregisterSignal = <function> defined @Scrap\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 SetTitleFormatted = <function> defined @SharedXML\PortraitFrame.lua:64
 NineSlice = <unnamed> {
 }
 Tab1 = ScrapVisualizerTab1 {
 }
 RegisterSignal = <function> defined @Scrap\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetPortraitToAsset = <function> defined @SharedXML\PortraitFrame.lua:32
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 0 = <userdata>
 CloseButton = ScrapVisualizerCloseButton {
 }
 TopTileStreaks = <unnamed> {
 }
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 SetPortraitToUnit = <function> defined @SharedXML\PortraitFrame.lua:36
 SetPortraitTexCoord = <function> defined @SharedXML\PortraitFrame.lua:48
 UnregisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SetTitleColor = <function> defined @SharedXML\PortraitFrame.lua:56
}
(*temporary) = "attempt to call method 'ToggleCurrent' (a nil value)"
`

**Additional context**

**Comment by WaitWut** [comment]
+1
**Error Log**
Date: 2020-02-22 07:15:50
ID: 1
Error occured in: Global
Count: 1
Message: [string "ScrapVisualizerButton:OnClick"] line 1:
   attempt to call method 'ToggleCurrent' (a nil value)
Debug:
   [C]: ToggleCurrent()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.6
  AtlasLootClassicData, vv1.4.6
  AtlasLootClassicDungeonsAndRaids, vv1.4.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  BagBrother, v
  Bagnon, v8.3.4
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.11.00
  ClassicQuestLog, v1.4.5-Classic
  DBMCore, v1.13.36
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  Informant, v8.2.6374 (SwimmingSeadragon)
  MBB, v1.0.0
  MooidesMountMod, v1.0
  MoveAnything, v17.1.0
  Questie, v5.7.1
  Recount, vv1.13.3b
  Scrap, v8.3.0
  ScrapMerchant, v
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.0.11303
  TitanClassicAmmo, v1.2.0.11303
  TitanClassicBag, v1.2.0.11303
  TitanClassicClock, v1.2.0.11303
  TitanClassicGold, v1.2.0.11303
  TitanClassicLocation, v1.2.0.11303
  TitanClassicLootType, v1.2.0.11303
  TitanClassicPerformance, v1.2.0.11303
  TitanClassicRegen, v1.2.0.11303
  TitanClassicRepair, v1.2.0.11303
  TitanClassicVolume, v1.2.0.11303
  TitanClassicXP, v1.2.0.11303
  TomPoints, v11303_06
  TomTom, vv11303-1.0.9
  WeakAuras, v2.16.6
  WIM, v3.8.5
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=6d5)
